/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ModerationApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ModerationApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ModerationApi_H_



#include "FastCommentsClient/ApiClient.h"

#include "FastCommentsClient/model/APIEmptyResponse.h"
#include "FastCommentsClient/model/APIError.h"
#include "FastCommentsClient/model/APIModerateGetUserBanPreferencesResponse.h"
#include "FastCommentsClient/model/AdjustCommentVotesParams.h"
#include "FastCommentsClient/model/AdjustVotesResponse.h"
#include "FastCommentsClient/model/AwardUserBadgeResponse.h"
#include "FastCommentsClient/model/BanUserFromCommentResult.h"
#include "FastCommentsClient/model/BanUserUndoParams.h"
#include "FastCommentsClient/model/BulkPreBanParams.h"
#include "FastCommentsClient/model/BulkPreBanSummary.h"
#include "FastCommentsClient/model/CommentsByIdsParams.h"
#include "FastCommentsClient/model/GetBannedUsersCountResponse.h"
#include "FastCommentsClient/model/GetBannedUsersFromCommentResponse.h"
#include "FastCommentsClient/model/GetCommentBanStatusResponse.h"
#include "FastCommentsClient/model/GetCommentTextResponse.h"
#include "FastCommentsClient/model/GetTenantManualBadgesResponse.h"
#include "FastCommentsClient/model/GetUserInternalProfileResponse.h"
#include "FastCommentsClient/model/GetUserManualBadgesResponse.h"
#include "FastCommentsClient/model/GetUserTrustFactorResponse.h"
#include "FastCommentsClient/model/ModerationAPIChildCommentsResponse.h"
#include "FastCommentsClient/model/ModerationAPICommentResponse.h"
#include "FastCommentsClient/model/ModerationAPICountCommentsResponse.h"
#include "FastCommentsClient/model/ModerationAPIGetCommentIdsResponse.h"
#include "FastCommentsClient/model/ModerationAPIGetCommentsResponse.h"
#include "FastCommentsClient/model/ModerationAPIGetLogsResponse.h"
#include "FastCommentsClient/model/ModerationCommentSearchResponse.h"
#include "FastCommentsClient/model/ModerationExportResponse.h"
#include "FastCommentsClient/model/ModerationExportStatusResponse.h"
#include "FastCommentsClient/model/ModerationPageSearchResponse.h"
#include "FastCommentsClient/model/ModerationSiteSearchResponse.h"
#include "FastCommentsClient/model/ModerationSuggestResponse.h"
#include "FastCommentsClient/model/ModerationUserSearchResponse.h"
#include "FastCommentsClient/model/PostRemoveCommentResponse.h"
#include "FastCommentsClient/model/PreBanSummary.h"
#include "FastCommentsClient/model/RemoveUserBadgeResponse.h"
#include "FastCommentsClient/model/SetCommentApprovedResponse.h"
#include "FastCommentsClient/model/SetCommentTextParams.h"
#include "FastCommentsClient/model/SetCommentTextResponse.h"
#include "FastCommentsClient/model/SetUserTrustFactorResponse.h"
#include "FastCommentsClient/model/VoteDeleteResponse.h"
#include "FastCommentsClient/model/VoteResponse.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ModerationApi 
{
public:

    explicit ModerationApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ModerationApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="voteId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<VoteDeleteResponse>> deleteModerationVote(
        utility::string_t commentId,
        utility::string_t voteId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="page"> (optional, default to 0.0)</param>
    /// <param name="count"> (optional, default to 0.0)</param>
    /// <param name="textSearch"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="byIPFromComment"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="filters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchFilters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sorts"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="demo"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationAPIGetCommentsResponse>> getApiComments(
        boost::optional<double> page,
        boost::optional<double> count,
        boost::optional<utility::string_t> textSearch,
        boost::optional<utility::string_t> byIPFromComment,
        boost::optional<utility::string_t> filters,
        boost::optional<utility::string_t> searchFilters,
        boost::optional<utility::string_t> sorts,
        boost::optional<bool> demo,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="batchJobId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationExportStatusResponse>> getApiExportStatus(
        boost::optional<utility::string_t> batchJobId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="textSearch"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="byIPFromComment"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="filters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchFilters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="afterId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="demo"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationAPIGetCommentIdsResponse>> getApiIds(
        boost::optional<utility::string_t> textSearch,
        boost::optional<utility::string_t> byIPFromComment,
        boost::optional<utility::string_t> filters,
        boost::optional<utility::string_t> searchFilters,
        boost::optional<utility::string_t> afterId,
        boost::optional<bool> demo,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetBannedUsersFromCommentResponse>> getBanUsersFromComment(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetCommentBanStatusResponse>> getCommentBanStatus(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationAPIChildCommentsResponse>> getCommentChildren(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="textSearch"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="byIPFromComment"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="filter"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchFilters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="demo"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationAPICountCommentsResponse>> getCount(
        boost::optional<utility::string_t> textSearch,
        boost::optional<utility::string_t> byIPFromComment,
        boost::optional<utility::string_t> filter,
        boost::optional<utility::string_t> searchFilters,
        boost::optional<bool> demo,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetBannedUsersCountResponse>> getCounts(
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationAPIGetLogsResponse>> getLogs(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetTenantManualBadgesResponse>> getManualBadges(
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="badgesUserId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="commentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetUserManualBadgesResponse>> getManualBadgesForUser(
        boost::optional<utility::string_t> badgesUserId,
        boost::optional<utility::string_t> commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="includeEmail"> (optional, default to false)</param>
    /// <param name="includeIP"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationAPICommentResponse>> getModerationComment(
        utility::string_t commentId,
        boost::optional<bool> includeEmail,
        boost::optional<bool> includeIP,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetCommentTextResponse>> getModerationCommentText(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="includeByUserIdAndEmail"> (optional, default to false)</param>
    /// <param name="includeByIP"> (optional, default to false)</param>
    /// <param name="includeByEmailDomain"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<PreBanSummary>> getPreBanSummary(
        utility::string_t commentId,
        boost::optional<bool> includeByUserIdAndEmail,
        boost::optional<bool> includeByIP,
        boost::optional<bool> includeByEmailDomain,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="value"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="filters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchFilters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationCommentSearchResponse>> getSearchCommentsSummary(
        boost::optional<utility::string_t> value,
        boost::optional<utility::string_t> filters,
        boost::optional<utility::string_t> searchFilters,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="value"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationPageSearchResponse>> getSearchPages(
        boost::optional<utility::string_t> value,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="value"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationSiteSearchResponse>> getSearchSites(
        boost::optional<utility::string_t> value,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="textSearch"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationSuggestResponse>> getSearchSuggest(
        boost::optional<utility::string_t> textSearch,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="value"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationUserSearchResponse>> getSearchUsers(
        boost::optional<utility::string_t> value,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="userId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetUserTrustFactorResponse>> getTrustFactor(
        boost::optional<utility::string_t> userId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIModerateGetUserBanPreferencesResponse>> getUserBanPreference(
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<GetUserInternalProfileResponse>> getUserInternalProfile(
        boost::optional<utility::string_t> commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="adjustCommentVotesParams"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AdjustVotesResponse>> postAdjustCommentVotes(
        utility::string_t commentId,
        std::shared_ptr<AdjustCommentVotesParams> adjustCommentVotesParams,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="textSearch"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="byIPFromComment"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="filters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchFilters"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sorts"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationExportResponse>> postApiExport(
        boost::optional<utility::string_t> textSearch,
        boost::optional<utility::string_t> byIPFromComment,
        boost::optional<utility::string_t> filters,
        boost::optional<utility::string_t> searchFilters,
        boost::optional<utility::string_t> sorts,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="banEmail"> (optional, default to false)</param>
    /// <param name="banEmailDomain"> (optional, default to false)</param>
    /// <param name="banIP"> (optional, default to false)</param>
    /// <param name="deleteAllUsersComments"> (optional, default to false)</param>
    /// <param name="bannedUntil"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="isShadowBan"> (optional, default to false)</param>
    /// <param name="updateId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="banReason"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<BanUserFromCommentResult>> postBanUserFromComment(
        utility::string_t commentId,
        boost::optional<bool> banEmail,
        boost::optional<bool> banEmailDomain,
        boost::optional<bool> banIP,
        boost::optional<bool> deleteAllUsersComments,
        boost::optional<utility::string_t> bannedUntil,
        boost::optional<bool> isShadowBan,
        boost::optional<utility::string_t> updateId,
        boost::optional<utility::string_t> banReason,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="banUserUndoParams"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> postBanUserUndo(
        std::shared_ptr<BanUserUndoParams> banUserUndoParams,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="bulkPreBanParams"></param>
    /// <param name="includeByUserIdAndEmail"> (optional, default to false)</param>
    /// <param name="includeByIP"> (optional, default to false)</param>
    /// <param name="includeByEmailDomain"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<BulkPreBanSummary>> postBulkPreBanSummary(
        std::shared_ptr<BulkPreBanParams> bulkPreBanParams,
        boost::optional<bool> includeByUserIdAndEmail,
        boost::optional<bool> includeByIP,
        boost::optional<bool> includeByEmailDomain,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentsByIdsParams"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ModerationAPIChildCommentsResponse>> postCommentsByIds(
        std::shared_ptr<CommentsByIdsParams> commentsByIdsParams,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> postFlagComment(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<PostRemoveCommentResponse>> postRemoveComment(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> postRestoreDeletedComment(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="approved"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<SetCommentApprovedResponse>> postSetCommentApprovalStatus(
        utility::string_t commentId,
        boost::optional<bool> approved,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="reviewed"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> postSetCommentReviewStatus(
        utility::string_t commentId,
        boost::optional<bool> reviewed,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="spam"> (optional, default to false)</param>
    /// <param name="permNotSpam"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> postSetCommentSpamStatus(
        utility::string_t commentId,
        boost::optional<bool> spam,
        boost::optional<bool> permNotSpam,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="setCommentTextParams"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<SetCommentTextResponse>> postSetCommentText(
        utility::string_t commentId,
        std::shared_ptr<SetCommentTextParams> setCommentTextParams,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> postUnFlagComment(
        utility::string_t commentId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="commentId"></param>
    /// <param name="direction"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<VoteResponse>> postVote(
        utility::string_t commentId,
        boost::optional<utility::string_t> direction,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="badgeId"></param>
    /// <param name="userId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="commentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="broadcastId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AwardUserBadgeResponse>> putAwardBadge(
        utility::string_t badgeId,
        boost::optional<utility::string_t> userId,
        boost::optional<utility::string_t> commentId,
        boost::optional<utility::string_t> broadcastId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="urlId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> putCloseThread(
        utility::string_t urlId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="badgeId"></param>
    /// <param name="userId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="commentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="broadcastId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<RemoveUserBadgeResponse>> putRemoveBadge(
        utility::string_t badgeId,
        boost::optional<utility::string_t> userId,
        boost::optional<utility::string_t> commentId,
        boost::optional<utility::string_t> broadcastId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="urlId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<APIEmptyResponse>> putReopenThread(
        utility::string_t urlId,
        boost::optional<utility::string_t> sso
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="userId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="trustFactor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<SetUserTrustFactorResponse>> setTrustFactor(
        boost::optional<utility::string_t> userId,
        boost::optional<utility::string_t> trustFactor,
        boost::optional<utility::string_t> sso
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ModerationApi_H_ */

