/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PublicApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_PublicApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_PublicApi_H_



#include "FastCommentsClient/ApiClient.h"

#include "FastCommentsClient/model/APIEmptyResponse.h"
#include "FastCommentsClient/model/APIError.h"
#include "FastCommentsClient/model/BlockSuccess.h"
#include "FastCommentsClient/model/ChangeCommentPinStatusResponse.h"
#include "FastCommentsClient/model/CheckBlockedCommentsResponse.h"
#include "FastCommentsClient/model/CommentData.h"
#include "FastCommentsClient/model/CommentTextUpdateRequest.h"
#include "FastCommentsClient/model/CreateFeedPostParams.h"
#include "FastCommentsClient/model/CreateFeedPostResponse.h"
#include "FastCommentsClient/model/CreateV1PageReact.h"
#include "FastCommentsClient/model/DeleteFeedPostPublicResponse.h"
#include "FastCommentsClient/model/FeedPostsStatsResponse.h"
#include "FastCommentsClient/model/GetCommentVoteUserNamesSuccessResponse.h"
#include "FastCommentsClient/model/GetCommentsForUserResponse.h"
#include "FastCommentsClient/model/GetCommentsResponseWithPresence_PublicComment_.h"
#include "FastCommentsClient/model/GetEventLogResponse.h"
#include "FastCommentsClient/model/GetGifsSearchResponse.h"
#include "FastCommentsClient/model/GetGifsTrendingResponse.h"
#include "FastCommentsClient/model/GetMyNotificationsResponse.h"
#include "FastCommentsClient/model/GetPublicPagesResponse.h"
#include "FastCommentsClient/model/GetTranslationsResponse.h"
#include "FastCommentsClient/model/GetUserNotificationCountResponse.h"
#include "FastCommentsClient/model/GetUserPresenceStatusesResponse.h"
#include "FastCommentsClient/model/GetV1PageLikes.h"
#include "FastCommentsClient/model/GetV2PageReactUsersResponse.h"
#include "FastCommentsClient/model/GetV2PageReacts.h"
#include "FastCommentsClient/model/GifGetLargeResponse.h"
#include "FastCommentsClient/HttpContent.h"
#include "FastCommentsClient/model/PageUsersInfoResponse.h"
#include "FastCommentsClient/model/PageUsersOfflineResponse.h"
#include "FastCommentsClient/model/PageUsersOnlineResponse.h"
#include "FastCommentsClient/model/PagesSortBy.h"
#include "FastCommentsClient/model/PublicAPIDeleteCommentResponse.h"
#include "FastCommentsClient/model/PublicAPIGetCommentTextResponse.h"
#include "FastCommentsClient/model/PublicAPISetCommentTextResponse.h"
#include "FastCommentsClient/model/PublicBlockFromCommentParams.h"
#include "FastCommentsClient/model/PublicFeedPostsResponse.h"
#include "FastCommentsClient/model/ReactBodyParams.h"
#include "FastCommentsClient/model/ReactFeedPostResponse.h"
#include "FastCommentsClient/model/ResetUserNotificationsResponse.h"
#include "FastCommentsClient/model/SaveCommentsResponseWithPresence.h"
#include "FastCommentsClient/model/SearchUsersResult.h"
#include "FastCommentsClient/model/SizePreset.h"
#include "FastCommentsClient/model/SortDirections.h"
#include "FastCommentsClient/model/UnblockSuccess.h"
#include "FastCommentsClient/model/UpdateFeedPostParams.h"
#include "FastCommentsClient/model/UpdateUserNotificationCommentSubscriptionStatusResponse.h"
#include "FastCommentsClient/model/UpdateUserNotificationPageSubscriptionStatusResponse.h"
#include "FastCommentsClient/model/UpdateUserNotificationStatusResponse.h"
#include "FastCommentsClient/model/UploadImageResponse.h"
#include "FastCommentsClient/model/UserReactsResponse.h"
#include "FastCommentsClient/model/VoteBodyParams.h"
#include "FastCommentsClient/model/VoteDeleteResponse.h"
#include "FastCommentsClient/model/VoteResponse.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  PublicApi 
{
public:

    explicit PublicApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~PublicApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="publicBlockFromCommentParams"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiBlockFromCommentPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        std::shared_ptr<PublicBlockFromCommentParams> publicBlockFromCommentParams;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<BlockSuccess>> blockFromCommentPublic(
        const ApiBlockFromCommentPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentIds">A comma separated list of comment ids.</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiCheckedCommentsForBlockedRequest
    {
        utility::string_t tenantId;
        utility::string_t commentIds;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<CheckBlockedCommentsResponse>> checkedCommentsForBlocked(
        const ApiCheckedCommentsForBlockedRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="commentData"></param>
    /// <param name="sessionId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiCreateCommentPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        utility::string_t broadcastId;
        std::shared_ptr<CommentData> commentData;
        boost::optional<utility::string_t> sessionId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<SaveCommentsResponseWithPresence>> createCommentPublic(
        const ApiCreateCommentPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="createFeedPostParams"></param>
    /// <param name="broadcastId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiCreateFeedPostPublicRequest
    {
        utility::string_t tenantId;
        std::shared_ptr<CreateFeedPostParams> createFeedPostParams;
        boost::optional<utility::string_t> broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<CreateFeedPostResponse>> createFeedPostPublic(
        const ApiCreateFeedPostPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="title"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiCreateV1PageReactRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        boost::optional<utility::string_t> title;
    };
    pplx::task<std::shared_ptr<CreateV1PageReact>> createV1PageReact(
        const ApiCreateV1PageReactRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="id"></param>
    /// <param name="title"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiCreateV2PageReactRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        utility::string_t id;
        boost::optional<utility::string_t> title;
    };
    pplx::task<std::shared_ptr<CreateV1PageReact>> createV2PageReact(
        const ApiCreateV2PageReactRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="editKey"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiDeleteCommentPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t broadcastId;
        boost::optional<utility::string_t> editKey;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<PublicAPIDeleteCommentResponse>> deleteCommentPublic(
        const ApiDeleteCommentPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="voteId"></param>
    /// <param name="urlId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="editKey"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiDeleteCommentVoteRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t voteId;
        utility::string_t urlId;
        utility::string_t broadcastId;
        boost::optional<utility::string_t> editKey;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<VoteDeleteResponse>> deleteCommentVote(
        const ApiDeleteCommentVoteRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="postId"></param>
    /// <param name="broadcastId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiDeleteFeedPostPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t postId;
        boost::optional<utility::string_t> broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<DeleteFeedPostPublicResponse>> deleteFeedPostPublic(
        const ApiDeleteFeedPostPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    struct ApiDeleteV1PageReactRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
    };
    pplx::task<std::shared_ptr<CreateV1PageReact>> deleteV1PageReact(
        const ApiDeleteV1PageReactRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="id"></param>
    struct ApiDeleteV2PageReactRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        utility::string_t id;
    };
    pplx::task<std::shared_ptr<CreateV1PageReact>> deleteV2PageReact(
        const ApiDeleteV2PageReactRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="isFlagged"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiFlagCommentPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        bool isFlagged;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<APIEmptyResponse>> flagCommentPublic(
        const ApiFlagCommentPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="editKey"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetCommentTextRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        boost::optional<utility::string_t> editKey;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<PublicAPIGetCommentTextResponse>> getCommentText(
        const ApiGetCommentTextRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="dir"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetCommentVoteUserNamesRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        int32_t dir;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<GetCommentVoteUserNamesSuccessResponse>> getCommentVoteUserNames(
        const ApiGetCommentVoteUserNamesRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="userId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="direction"> (optional, default to new SortDirections())</param>
    /// <param name="repliesToUserId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0.0)</param>
    /// <param name="includei10n"> (optional, default to false)</param>
    /// <param name="locale"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="isCrawler"> (optional, default to false)</param>
    struct ApiGetCommentsForUserRequest
    {
        boost::optional<utility::string_t> userId;
        boost::optional<std::shared_ptr<SortDirections>> direction;
        boost::optional<utility::string_t> repliesToUserId;
        boost::optional<double> page;
        boost::optional<bool> includei10n;
        boost::optional<utility::string_t> locale;
        boost::optional<bool> isCrawler;
    };
    pplx::task<std::shared_ptr<GetCommentsForUserResponse>> getCommentsForUser(
        const ApiGetCommentsForUserRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    ///  req tenantId urlId
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="direction"> (optional, default to new SortDirections())</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="skip"> (optional, default to 0)</param>
    /// <param name="skipChildren"> (optional, default to 0)</param>
    /// <param name="limit"> (optional, default to 0)</param>
    /// <param name="limitChildren"> (optional, default to 0)</param>
    /// <param name="countChildren"> (optional, default to false)</param>
    /// <param name="fetchPageForCommentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="includeConfig"> (optional, default to false)</param>
    /// <param name="countAll"> (optional, default to false)</param>
    /// <param name="includei10n"> (optional, default to false)</param>
    /// <param name="locale"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="modules"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="isCrawler"> (optional, default to false)</param>
    /// <param name="includeNotificationCount"> (optional, default to false)</param>
    /// <param name="asTree"> (optional, default to false)</param>
    /// <param name="maxTreeDepth"> (optional, default to 0)</param>
    /// <param name="useFullTranslationIds"> (optional, default to false)</param>
    /// <param name="parentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchText"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="hashTags"> (optional, default to std::vector&lt;std::shared_ptr&lt;utility::string_t&gt;&gt;())</param>
    /// <param name="userId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="customConfigStr"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="afterCommentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="beforeCommentId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetCommentsPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        boost::optional<int32_t> page;
        boost::optional<std::shared_ptr<SortDirections>> direction;
        boost::optional<utility::string_t> sso;
        boost::optional<int32_t> skip;
        boost::optional<int32_t> skipChildren;
        boost::optional<int32_t> limit;
        boost::optional<int32_t> limitChildren;
        boost::optional<bool> countChildren;
        boost::optional<utility::string_t> fetchPageForCommentId;
        boost::optional<bool> includeConfig;
        boost::optional<bool> countAll;
        boost::optional<bool> includei10n;
        boost::optional<utility::string_t> locale;
        boost::optional<utility::string_t> modules;
        boost::optional<bool> isCrawler;
        boost::optional<bool> includeNotificationCount;
        boost::optional<bool> asTree;
        boost::optional<int32_t> maxTreeDepth;
        boost::optional<bool> useFullTranslationIds;
        boost::optional<utility::string_t> parentId;
        boost::optional<utility::string_t> searchText;
        boost::optional<std::vector<utility::string_t>> hashTags;
        boost::optional<utility::string_t> userId;
        boost::optional<utility::string_t> customConfigStr;
        boost::optional<utility::string_t> afterCommentId;
        boost::optional<utility::string_t> beforeCommentId;
    };
    pplx::task<std::shared_ptr<GetCommentsResponseWithPresence_PublicComment_>> getCommentsPublic(
        const ApiGetCommentsPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    ///  req tenantId urlId userIdWS
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="userIdWS"></param>
    /// <param name="startTime"></param>
    /// <param name="endTime"> (optional, default to 0L)</param>
    struct ApiGetEventLogRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        utility::string_t userIdWS;
        int64_t startTime;
        boost::optional<int64_t> endTime;
    };
    pplx::task<std::shared_ptr<GetEventLogResponse>> getEventLog(
        const ApiGetEventLogRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    ///  req tenantId afterId
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="afterId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="limit"> (optional, default to 0)</param>
    /// <param name="tags"> (optional, default to std::vector&lt;std::shared_ptr&lt;utility::string_t&gt;&gt;())</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="isCrawler"> (optional, default to false)</param>
    /// <param name="includeUserInfo"> (optional, default to false)</param>
    struct ApiGetFeedPostsPublicRequest
    {
        utility::string_t tenantId;
        boost::optional<utility::string_t> afterId;
        boost::optional<int32_t> limit;
        boost::optional<std::vector<utility::string_t>> tags;
        boost::optional<utility::string_t> sso;
        boost::optional<bool> isCrawler;
        boost::optional<bool> includeUserInfo;
    };
    pplx::task<std::shared_ptr<PublicFeedPostsResponse>> getFeedPostsPublic(
        const ApiGetFeedPostsPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="postIds"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetFeedPostsStatsRequest
    {
        utility::string_t tenantId;
        std::vector<utility::string_t> postIds;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<FeedPostsStatsResponse>> getFeedPostsStats(
        const ApiGetFeedPostsStatsRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="largeInternalURLSanitized"></param>
    struct ApiGetGifLargeRequest
    {
        utility::string_t tenantId;
        utility::string_t largeInternalURLSanitized;
    };
    pplx::task<std::shared_ptr<GifGetLargeResponse>> getGifLarge(
        const ApiGetGifLargeRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="search"></param>
    /// <param name="locale"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="rating"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0.0)</param>
    struct ApiGetGifsSearchRequest
    {
        utility::string_t tenantId;
        utility::string_t search;
        boost::optional<utility::string_t> locale;
        boost::optional<utility::string_t> rating;
        boost::optional<double> page;
    };
    pplx::task<std::shared_ptr<GetGifsSearchResponse>> getGifsSearch(
        const ApiGetGifsSearchRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="locale"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="rating"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0.0)</param>
    struct ApiGetGifsTrendingRequest
    {
        utility::string_t tenantId;
        boost::optional<utility::string_t> locale;
        boost::optional<utility::string_t> rating;
        boost::optional<double> page;
    };
    pplx::task<std::shared_ptr<GetGifsTrendingResponse>> getGifsTrending(
        const ApiGetGifsTrendingRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    ///  req tenantId urlId userIdWS
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="userIdWS"></param>
    /// <param name="startTime"></param>
    /// <param name="endTime"> (optional, default to 0L)</param>
    struct ApiGetGlobalEventLogRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        utility::string_t userIdWS;
        int64_t startTime;
        boost::optional<int64_t> endTime;
    };
    pplx::task<std::shared_ptr<GetEventLogResponse>> getGlobalEventLog(
        const ApiGetGlobalEventLogRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Past commenters on the page who are NOT currently online. Sorted by displayName. Use this after exhausting /users/online to render a \&quot;Members\&quot; section. Cursor pagination on commenterName: server walks the partial {tenantId, urlId, commenterName} index from afterName forward via $gt, no $skip cost.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId">Page URL identifier (cleaned server-side).</param>
    /// <param name="afterName">Cursor: pass nextAfterName from the previous response. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="afterUserId">Cursor tiebreaker: pass nextAfterUserId from the previous response. Required when afterName is set so name-ties don&#39;t drop entries. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetOfflineUsersRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        boost::optional<utility::string_t> afterName;
        boost::optional<utility::string_t> afterUserId;
    };
    pplx::task<std::shared_ptr<PageUsersOfflineResponse>> getOfflineUsers(
        const ApiGetOfflineUsersRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Currently-online viewers of a page: people whose websocket session is subscribed to the page right now. Returns anonCount + totalCount (room-wide subscribers, including anon viewers we don&#39;t enumerate).
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId">Page URL identifier (cleaned server-side).</param>
    /// <param name="afterName">Cursor: pass nextAfterName from the previous response. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="afterUserId">Cursor tiebreaker: pass nextAfterUserId from the previous response. Required when afterName is set so name-ties don&#39;t drop entries. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetOnlineUsersRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        boost::optional<utility::string_t> afterName;
        boost::optional<utility::string_t> afterUserId;
    };
    pplx::task<std::shared_ptr<PageUsersOnlineResponse>> getOnlineUsers(
        const ApiGetOnlineUsersRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// List pages for a tenant. Used by the FChat desktop client to populate its room list. Requires &#x60;enableFChat&#x60; to be true on the resolved custom config for each page. Pages that require SSO are filtered against the requesting user&#39;s group access.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="cursor">Opaque pagination cursor returned as &#x60;nextCursor&#x60; from a prior request. Tied to the same &#x60;sortBy&#x60;. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="limit">1..200, default 50 (optional, default to 0)</param>
    /// <param name="q">Optional case-insensitive title prefix filter. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sortBy">Sort order. &#x60;updatedAt&#x60; (default, newest first), &#x60;commentCount&#x60; (most comments first), or &#x60;title&#x60; (alphabetical). (optional, default to new PagesSortBy())</param>
    /// <param name="hasComments">If true, only return pages with at least one comment. (optional, default to false)</param>
    struct ApiGetPagesPublicRequest
    {
        utility::string_t tenantId;
        boost::optional<utility::string_t> cursor;
        boost::optional<int32_t> limit;
        boost::optional<utility::string_t> q;
        boost::optional<std::shared_ptr<PagesSortBy>> sortBy;
        boost::optional<bool> hasComments;
    };
    pplx::task<std::shared_ptr<GetPublicPagesResponse>> getPagesPublic(
        const ApiGetPagesPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="r_namespace"></param>
    /// <param name="component"></param>
    /// <param name="locale"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="useFullTranslationIds"> (optional, default to false)</param>
    struct ApiGetTranslationsRequest
    {
        utility::string_t r_namespace;
        utility::string_t component;
        boost::optional<utility::string_t> locale;
        boost::optional<bool> useFullTranslationIds;
    };
    pplx::task<std::shared_ptr<GetTranslationsResponse>> getTranslations(
        const ApiGetTranslationsRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetUserNotificationCountRequest
    {
        utility::string_t tenantId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<GetUserNotificationCountResponse>> getUserNotificationCount(
        const ApiGetUserNotificationCountRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId">Used to determine whether the current page is subscribed. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    /// <param name="afterId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="includeContext"> (optional, default to false)</param>
    /// <param name="afterCreatedAt"> (optional, default to 0L)</param>
    /// <param name="unreadOnly"> (optional, default to false)</param>
    /// <param name="dmOnly"> (optional, default to false)</param>
    /// <param name="noDm"> (optional, default to false)</param>
    /// <param name="includeTranslations"> (optional, default to false)</param>
    /// <param name="includeTenantNotifications"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetUserNotificationsRequest
    {
        utility::string_t tenantId;
        boost::optional<utility::string_t> urlId;
        boost::optional<int32_t> pageSize;
        boost::optional<utility::string_t> afterId;
        boost::optional<bool> includeContext;
        boost::optional<int64_t> afterCreatedAt;
        boost::optional<bool> unreadOnly;
        boost::optional<bool> dmOnly;
        boost::optional<bool> noDm;
        boost::optional<bool> includeTranslations;
        boost::optional<bool> includeTenantNotifications;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<GetMyNotificationsResponse>> getUserNotifications(
        const ApiGetUserNotificationsRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlIdWS"></param>
    /// <param name="userIds"></param>
    struct ApiGetUserPresenceStatusesRequest
    {
        utility::string_t tenantId;
        utility::string_t urlIdWS;
        utility::string_t userIds;
    };
    pplx::task<std::shared_ptr<GetUserPresenceStatusesResponse>> getUserPresenceStatuses(
        const ApiGetUserPresenceStatusesRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="postIds"> (optional, default to std::vector&lt;std::shared_ptr&lt;utility::string_t&gt;&gt;())</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiGetUserReactsPublicRequest
    {
        utility::string_t tenantId;
        boost::optional<std::vector<utility::string_t>> postIds;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<UserReactsResponse>> getUserReactsPublic(
        const ApiGetUserReactsPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Bulk user info for a tenant. Given userIds, return display info from User / SSOUser. Used by the comment widget to enrich users that just appeared via a presence event. No page context: privacy is enforced uniformly (private profiles are masked).
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="ids">Comma-delimited userIds.</param>
    struct ApiGetUsersInfoRequest
    {
        utility::string_t tenantId;
        utility::string_t ids;
    };
    pplx::task<std::shared_ptr<PageUsersInfoResponse>> getUsersInfo(
        const ApiGetUsersInfoRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    struct ApiGetV1PageLikesRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
    };
    pplx::task<std::shared_ptr<GetV1PageLikes>> getV1PageLikes(
        const ApiGetV1PageLikesRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="id"></param>
    struct ApiGetV2PageReactUsersRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        utility::string_t id;
    };
    pplx::task<std::shared_ptr<GetV2PageReactUsersResponse>> getV2PageReactUsers(
        const ApiGetV2PageReactUsersRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    struct ApiGetV2PageReactsRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
    };
    pplx::task<std::shared_ptr<GetV2PageReacts>> getV2PageReacts(
        const ApiGetV2PageReactsRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiLockCommentRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<APIEmptyResponse>> lockComment(
        const ApiLockCommentRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    struct ApiLogoutPublicRequest
    {
    };
    pplx::task<std::shared_ptr<APIEmptyResponse>> logoutPublic(
        const ApiLogoutPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiPinCommentRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<ChangeCommentPinStatusResponse>> pinComment(
        const ApiPinCommentRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="postId"></param>
    /// <param name="reactBodyParams"></param>
    /// <param name="isUndo"> (optional, default to false)</param>
    /// <param name="broadcastId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiReactFeedPostPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t postId;
        std::shared_ptr<ReactBodyParams> reactBodyParams;
        boost::optional<bool> isUndo;
        boost::optional<utility::string_t> broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<ReactFeedPostResponse>> reactFeedPostPublic(
        const ApiReactFeedPostPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiResetUserNotificationCountRequest
    {
        utility::string_t tenantId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<ResetUserNotificationsResponse>> resetUserNotificationCount(
        const ApiResetUserNotificationCountRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="afterId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="afterCreatedAt"> (optional, default to 0L)</param>
    /// <param name="unreadOnly"> (optional, default to false)</param>
    /// <param name="dmOnly"> (optional, default to false)</param>
    /// <param name="noDm"> (optional, default to false)</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiResetUserNotificationsRequest
    {
        utility::string_t tenantId;
        boost::optional<utility::string_t> afterId;
        boost::optional<int64_t> afterCreatedAt;
        boost::optional<bool> unreadOnly;
        boost::optional<bool> dmOnly;
        boost::optional<bool> noDm;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<ResetUserNotificationsResponse>> resetUserNotifications(
        const ApiResetUserNotificationsRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="usernameStartsWith"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="mentionGroupIds"> (optional, default to std::vector&lt;std::shared_ptr&lt;utility::string_t&gt;&gt;())</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchSection"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiSearchUsersRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        boost::optional<utility::string_t> usernameStartsWith;
        boost::optional<std::vector<utility::string_t>> mentionGroupIds;
        boost::optional<utility::string_t> sso;
        boost::optional<utility::string_t> searchSection;
    };
    pplx::task<std::shared_ptr<SearchUsersResult>> searchUsers(
        const ApiSearchUsersRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="commentTextUpdateRequest"></param>
    /// <param name="editKey"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiSetCommentTextRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t broadcastId;
        std::shared_ptr<CommentTextUpdateRequest> commentTextUpdateRequest;
        boost::optional<utility::string_t> editKey;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<PublicAPISetCommentTextResponse>> setCommentText(
        const ApiSetCommentTextRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="publicBlockFromCommentParams"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUnBlockCommentPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        std::shared_ptr<PublicBlockFromCommentParams> publicBlockFromCommentParams;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<UnblockSuccess>> unBlockCommentPublic(
        const ApiUnBlockCommentPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUnLockCommentRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<APIEmptyResponse>> unLockComment(
        const ApiUnLockCommentRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUnPinCommentRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<ChangeCommentPinStatusResponse>> unPinComment(
        const ApiUnPinCommentRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="postId"></param>
    /// <param name="updateFeedPostParams"></param>
    /// <param name="broadcastId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUpdateFeedPostPublicRequest
    {
        utility::string_t tenantId;
        utility::string_t postId;
        std::shared_ptr<UpdateFeedPostParams> updateFeedPostParams;
        boost::optional<utility::string_t> broadcastId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<CreateFeedPostResponse>> updateFeedPostPublic(
        const ApiUpdateFeedPostPublicRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Enable or disable notifications for a specific comment.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="notificationId"></param>
    /// <param name="optedInOrOut"></param>
    /// <param name="commentId"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUpdateUserNotificationCommentSubscriptionStatusRequest
    {
        utility::string_t tenantId;
        utility::string_t notificationId;
        utility::string_t optedInOrOut;
        utility::string_t commentId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<UpdateUserNotificationCommentSubscriptionStatusResponse>> updateUserNotificationCommentSubscriptionStatus(
        const ApiUpdateUserNotificationCommentSubscriptionStatusRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Enable or disable notifications for a page. When users are subscribed to a page, notifications are created for new root comments, and also
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="urlId"></param>
    /// <param name="url"></param>
    /// <param name="pageTitle"></param>
    /// <param name="subscribedOrUnsubscribed"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUpdateUserNotificationPageSubscriptionStatusRequest
    {
        utility::string_t tenantId;
        utility::string_t urlId;
        utility::string_t url;
        utility::string_t pageTitle;
        utility::string_t subscribedOrUnsubscribed;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<UpdateUserNotificationPageSubscriptionStatusResponse>> updateUserNotificationPageSubscriptionStatus(
        const ApiUpdateUserNotificationPageSubscriptionStatusRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="notificationId"></param>
    /// <param name="newStatus"></param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUpdateUserNotificationStatusRequest
    {
        utility::string_t tenantId;
        utility::string_t notificationId;
        utility::string_t newStatus;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<UpdateUserNotificationStatusResponse>> updateUserNotificationStatus(
        const ApiUpdateUserNotificationStatusRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Upload and resize an image
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="file"></param>
    /// <param name="sizePreset">Size preset: \&quot;Default\&quot; (1000x1000px) or \&quot;CrossPlatform\&quot; (creates sizes for popular devices) (optional, default to new SizePreset())</param>
    /// <param name="urlId">Page id that upload is happening from, to configure (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiUploadImageRequest
    {
        utility::string_t tenantId;
        std::shared_ptr<HttpContent> file;
        boost::optional<std::shared_ptr<SizePreset>> sizePreset;
        boost::optional<utility::string_t> urlId;
    };
    pplx::task<std::shared_ptr<UploadImageResponse>> uploadImage(
        const ApiUploadImageRequest& request
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="commentId"></param>
    /// <param name="urlId"></param>
    /// <param name="broadcastId"></param>
    /// <param name="voteBodyParams"></param>
    /// <param name="sessionId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sso"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    struct ApiVoteCommentRequest
    {
        utility::string_t tenantId;
        utility::string_t commentId;
        utility::string_t urlId;
        utility::string_t broadcastId;
        std::shared_ptr<VoteBodyParams> voteBodyParams;
        boost::optional<utility::string_t> sessionId;
        boost::optional<utility::string_t> sso;
    };
    pplx::task<std::shared_ptr<VoteResponse>> voteComment(
        const ApiVoteCommentRequest& request
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_PublicApi_H_ */

