/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/AdjustCommentVotesParams.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AdjustCommentVotesParams::AdjustCommentVotesParams()
{
    m_AdjustVoteAmount = 0.0;
    m_AdjustVoteAmountIsSet = false;
}

AdjustCommentVotesParams::~AdjustCommentVotesParams()
{
}

void AdjustCommentVotesParams::validate()
{
    // TODO: implement validation
}

web::json::value AdjustCommentVotesParams::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AdjustVoteAmountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("adjustVoteAmount"))] = ModelBase::toJson(m_AdjustVoteAmount);
    }

    return val;
}

bool AdjustCommentVotesParams::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("adjustVoteAmount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("adjustVoteAmount")));
        if(!fieldValue.is_null())
        {
            double refVal_setAdjustVoteAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAdjustVoteAmount);
            setAdjustVoteAmount(refVal_setAdjustVoteAmount);
            
        }
    }
    return ok;
}

void AdjustCommentVotesParams::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AdjustVoteAmountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("adjustVoteAmount")), m_AdjustVoteAmount));
    }
}

bool AdjustCommentVotesParams::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("adjustVoteAmount"))))
    {
        double refVal_setAdjustVoteAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("adjustVoteAmount"))), refVal_setAdjustVoteAmount );
        setAdjustVoteAmount(refVal_setAdjustVoteAmount);
    }
    return ok;
}


double AdjustCommentVotesParams::getAdjustVoteAmount() const
{
    return m_AdjustVoteAmount;
}

void AdjustCommentVotesParams::setAdjustVoteAmount(double value)
{
    m_AdjustVoteAmount = value;
    m_AdjustVoteAmountIsSet = true;
}

bool AdjustCommentVotesParams::adjustVoteAmountIsSet() const
{
    return m_AdjustVoteAmountIsSet;
}

void AdjustCommentVotesParams::unsetAdjustVoteAmount()
{
    m_AdjustVoteAmountIsSet = false;
}

}
}
}
}


