/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/AggregationResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AggregationResponse::AggregationResponse()
{
    m_StatusIsSet = false;
    m_DataIsSet = false;
    m_StatsIsSet = false;
}

AggregationResponse::~AggregationResponse()
{
}

void AggregationResponse::validate()
{
    // TODO: implement validation
}

web::json::value AggregationResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_DataIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("data"))] = ModelBase::toJson(m_Data);
    }
    if(m_StatsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("stats"))] = ModelBase::toJson(m_Stats);
    }

    return val;
}

bool AggregationResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("data"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("data")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AggregationItem>> refVal_setData;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData);
            setData(refVal_setData);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stats"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stats")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AggregationResponse_stats> refVal_setStats;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStats);
            setStats(refVal_setStats);
            
        }
    }
    return ok;
}

void AggregationResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_DataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("data")), m_Data));
    }
    if(m_StatsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stats")), m_Stats));
    }
}

bool AggregationResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("data"))))
    {
        std::vector<std::shared_ptr<AggregationItem>> refVal_setData;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("data"))), refVal_setData );
        setData(refVal_setData);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stats"))))
    {
        std::shared_ptr<AggregationResponse_stats> refVal_setStats;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stats"))), refVal_setStats );
        setStats(refVal_setStats);
    }
    return ok;
}


std::shared_ptr<APIStatus> AggregationResponse::getStatus() const
{
    return m_Status;
}


void AggregationResponse::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool AggregationResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void AggregationResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
std::vector<std::shared_ptr<AggregationItem>> AggregationResponse::getData() const
{
    return m_Data;
}


void AggregationResponse::setData(const std::vector<std::shared_ptr<AggregationItem>>& value)
{
    m_Data = value;
    m_DataIsSet = true;
}

bool AggregationResponse::dataIsSet() const
{
    return m_DataIsSet;
}

void AggregationResponse::unsetData()
{
    m_DataIsSet = false;
}
std::shared_ptr<AggregationResponse_stats> AggregationResponse::getStats() const
{
    return m_Stats;
}


void AggregationResponse::setStats(const std::shared_ptr<AggregationResponse_stats>& value)
{
    m_Stats = value;
    m_StatsIsSet = true;
}

bool AggregationResponse::statsIsSet() const
{
    return m_StatsIsSet;
}

void AggregationResponse::unsetStats()
{
    m_StatsIsSet = false;
}

}
}
}
}


