/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/AggregateResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AggregateResponse::AggregateResponse()
{
    m_StatusIsSet = false;
    m_DataIsSet = false;
    m_StatsIsSet = false;
    m_Reason = utility::conversions::to_string_t("");
    m_ReasonIsSet = false;
    m_Code = utility::conversions::to_string_t("");
    m_CodeIsSet = false;
    m_ValidResourceNamesIsSet = false;
}

AggregateResponse::~AggregateResponse()
{
}

void AggregateResponse::validate()
{
    // TODO: implement validation
}

web::json::value AggregateResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_DataIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("data"))] = ModelBase::toJson(m_Data);
    }
    if(m_StatsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("stats"))] = ModelBase::toJson(m_Stats);
    }
    if(m_ReasonIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("reason"))] = ModelBase::toJson(m_Reason);
    }
    if(m_CodeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }
    if(m_ValidResourceNamesIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("validResourceNames"))] = ModelBase::toJson(m_ValidResourceNames);
    }

    return val;
}

bool AggregateResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("data"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("data")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AggregationItem>> refVal_setData;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData);
            setData(refVal_setData);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stats"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stats")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AggregationResponse_stats> refVal_setStats;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStats);
            setStats(refVal_setStats);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reason")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setReason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReason);
            setReason(refVal_setReason);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("validResourceNames"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("validResourceNames")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setValidResourceNames;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValidResourceNames);
            setValidResourceNames(refVal_setValidResourceNames);
            
        }
    }
    return ok;
}

void AggregateResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_DataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("data")), m_Data));
    }
    if(m_StatsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stats")), m_Stats));
    }
    if(m_ReasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reason")), m_Reason));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
    if(m_ValidResourceNamesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("validResourceNames")), m_ValidResourceNames));
    }
}

bool AggregateResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("data"))))
    {
        std::vector<std::shared_ptr<AggregationItem>> refVal_setData;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("data"))), refVal_setData );
        setData(refVal_setData);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stats"))))
    {
        std::shared_ptr<AggregationResponse_stats> refVal_setStats;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stats"))), refVal_setStats );
        setStats(refVal_setStats);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        utility::string_t refVal_setReason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reason"))), refVal_setReason );
        setReason(refVal_setReason);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("validResourceNames"))))
    {
        std::vector<utility::string_t> refVal_setValidResourceNames;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("validResourceNames"))), refVal_setValidResourceNames );
        setValidResourceNames(refVal_setValidResourceNames);
    }
    return ok;
}


std::shared_ptr<APIStatus> AggregateResponse::getStatus() const
{
    return m_Status;
}


void AggregateResponse::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool AggregateResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void AggregateResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
std::vector<std::shared_ptr<AggregationItem>> AggregateResponse::getData() const
{
    return m_Data;
}


void AggregateResponse::setData(const std::vector<std::shared_ptr<AggregationItem>>& value)
{
    m_Data = value;
    m_DataIsSet = true;
}

bool AggregateResponse::dataIsSet() const
{
    return m_DataIsSet;
}

void AggregateResponse::unsetData()
{
    m_DataIsSet = false;
}
std::shared_ptr<AggregationResponse_stats> AggregateResponse::getStats() const
{
    return m_Stats;
}


void AggregateResponse::setStats(const std::shared_ptr<AggregationResponse_stats>& value)
{
    m_Stats = value;
    m_StatsIsSet = true;
}

bool AggregateResponse::statsIsSet() const
{
    return m_StatsIsSet;
}

void AggregateResponse::unsetStats()
{
    m_StatsIsSet = false;
}
utility::string_t AggregateResponse::getReason() const
{
    return m_Reason;
}


void AggregateResponse::setReason(const utility::string_t& value)
{
    m_Reason = value;
    m_ReasonIsSet = true;
}

bool AggregateResponse::reasonIsSet() const
{
    return m_ReasonIsSet;
}

void AggregateResponse::unsetReason()
{
    m_ReasonIsSet = false;
}
utility::string_t AggregateResponse::getCode() const
{
    return m_Code;
}


void AggregateResponse::setCode(const utility::string_t& value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool AggregateResponse::codeIsSet() const
{
    return m_CodeIsSet;
}

void AggregateResponse::unsetCode()
{
    m_CodeIsSet = false;
}
std::vector<utility::string_t> AggregateResponse::getValidResourceNames() const
{
    return m_ValidResourceNames;
}


void AggregateResponse::setValidResourceNames(const std::vector<utility::string_t>& value)
{
    m_ValidResourceNames = value;
    m_ValidResourceNamesIsSet = true;
}

bool AggregateResponse::validResourceNamesIsSet() const
{
    return m_ValidResourceNamesIsSet;
}

void AggregateResponse::unsetValidResourceNames()
{
    m_ValidResourceNamesIsSet = false;
}

}
}
}
}


