/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/APIDomainConfiguration.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

APIDomainConfiguration::APIDomainConfiguration()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Domain = utility::conversions::to_string_t("");
    m_DomainIsSet = false;
    m_EmailFromName = utility::conversions::to_string_t("");
    m_EmailFromNameIsSet = false;
    m_EmailFromEmail = utility::conversions::to_string_t("");
    m_EmailFromEmailIsSet = false;
    m_EmailHeadersIsSet = false;
    m_WpSyncToken = utility::conversions::to_string_t("");
    m_WpSyncTokenIsSet = false;
    m_WpSynced = false;
    m_WpSyncedIsSet = false;
    m_WpURL = utility::conversions::to_string_t("");
    m_WpURLIsSet = false;
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
    m_AutoAddedDate = utility::datetime();
    m_AutoAddedDateIsSet = false;
    m_SiteTypeIsSet = false;
    m_LogoSrc = utility::conversions::to_string_t("");
    m_LogoSrcIsSet = false;
    m_LogoSrc100px = utility::conversions::to_string_t("");
    m_LogoSrc100pxIsSet = false;
    m_FooterUnsubscribeURL = utility::conversions::to_string_t("");
    m_FooterUnsubscribeURLIsSet = false;
    m_DisableUnsubscribeLinks = false;
    m_DisableUnsubscribeLinksIsSet = false;
}

APIDomainConfiguration::~APIDomainConfiguration()
{
}

void APIDomainConfiguration::validate()
{
    // TODO: implement validation
}

web::json::value APIDomainConfiguration::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_DomainIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("domain"))] = ModelBase::toJson(m_Domain);
    }
    if(m_EmailFromNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("emailFromName"))] = ModelBase::toJson(m_EmailFromName);
    }
    if(m_EmailFromEmailIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("emailFromEmail"))] = ModelBase::toJson(m_EmailFromEmail);
    }
    if(m_EmailHeadersIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("emailHeaders"))] = ModelBase::toJson(m_EmailHeaders);
    }
    if(m_WpSyncTokenIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("wpSyncToken"))] = ModelBase::toJson(m_WpSyncToken);
    }
    if(m_WpSyncedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("wpSynced"))] = ModelBase::toJson(m_WpSynced);
    }
    if(m_WpURLIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("wpURL"))] = ModelBase::toJson(m_WpURL);
    }
    if(m_CreatedAtIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_AutoAddedDateIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("autoAddedDate"))] = ModelBase::toJson(m_AutoAddedDate);
    }
    if(m_SiteTypeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("siteType"))] = ModelBase::toJson(m_SiteType);
    }
    if(m_LogoSrcIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("logoSrc"))] = ModelBase::toJson(m_LogoSrc);
    }
    if(m_LogoSrc100pxIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("logoSrc100px"))] = ModelBase::toJson(m_LogoSrc100px);
    }
    if(m_FooterUnsubscribeURLIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("footerUnsubscribeURL"))] = ModelBase::toJson(m_FooterUnsubscribeURL);
    }
    if(m_DisableUnsubscribeLinksIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("disableUnsubscribeLinks"))] = ModelBase::toJson(m_DisableUnsubscribeLinks);
    }

    return val;
}

bool APIDomainConfiguration::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("domain"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("domain")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDomain;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDomain);
            setDomain(refVal_setDomain);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("emailFromName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("emailFromName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmailFromName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmailFromName);
            setEmailFromName(refVal_setEmailFromName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("emailFromEmail"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("emailFromEmail")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmailFromEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmailFromEmail);
            setEmailFromEmail(refVal_setEmailFromEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("emailHeaders"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("emailHeaders")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setEmailHeaders;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmailHeaders);
            setEmailHeaders(refVal_setEmailHeaders);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("wpSyncToken"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("wpSyncToken")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWpSyncToken;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWpSyncToken);
            setWpSyncToken(refVal_setWpSyncToken);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("wpSynced"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("wpSynced")));
        if(!fieldValue.is_null())
        {
            bool refVal_setWpSynced;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWpSynced);
            setWpSynced(refVal_setWpSynced);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("wpURL"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("wpURL")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWpURL;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWpURL);
            setWpURL(refVal_setWpURL);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("autoAddedDate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("autoAddedDate")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setAutoAddedDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAutoAddedDate);
            setAutoAddedDate(refVal_setAutoAddedDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("siteType"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("siteType")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ImportedSiteType> refVal_setSiteType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSiteType);
            setSiteType(refVal_setSiteType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("logoSrc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("logoSrc")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLogoSrc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogoSrc);
            setLogoSrc(refVal_setLogoSrc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("logoSrc100px"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("logoSrc100px")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLogoSrc100px;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogoSrc100px);
            setLogoSrc100px(refVal_setLogoSrc100px);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("footerUnsubscribeURL"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("footerUnsubscribeURL")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFooterUnsubscribeURL;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFooterUnsubscribeURL);
            setFooterUnsubscribeURL(refVal_setFooterUnsubscribeURL);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("disableUnsubscribeLinks"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("disableUnsubscribeLinks")));
        if(!fieldValue.is_null())
        {
            bool refVal_setDisableUnsubscribeLinks;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDisableUnsubscribeLinks);
            setDisableUnsubscribeLinks(refVal_setDisableUnsubscribeLinks);
            
        }
    }
    return ok;
}

void APIDomainConfiguration::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_DomainIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("domain")), m_Domain));
    }
    if(m_EmailFromNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("emailFromName")), m_EmailFromName));
    }
    if(m_EmailFromEmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("emailFromEmail")), m_EmailFromEmail));
    }
    if(m_EmailHeadersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("emailHeaders")), m_EmailHeaders));
    }
    if(m_WpSyncTokenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("wpSyncToken")), m_WpSyncToken));
    }
    if(m_WpSyncedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("wpSynced")), m_WpSynced));
    }
    if(m_WpURLIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("wpURL")), m_WpURL));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_AutoAddedDateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("autoAddedDate")), m_AutoAddedDate));
    }
    if(m_SiteTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("siteType")), m_SiteType));
    }
    if(m_LogoSrcIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("logoSrc")), m_LogoSrc));
    }
    if(m_LogoSrc100pxIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("logoSrc100px")), m_LogoSrc100px));
    }
    if(m_FooterUnsubscribeURLIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("footerUnsubscribeURL")), m_FooterUnsubscribeURL));
    }
    if(m_DisableUnsubscribeLinksIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("disableUnsubscribeLinks")), m_DisableUnsubscribeLinks));
    }
}

bool APIDomainConfiguration::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("domain"))))
    {
        utility::string_t refVal_setDomain;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("domain"))), refVal_setDomain );
        setDomain(refVal_setDomain);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("emailFromName"))))
    {
        utility::string_t refVal_setEmailFromName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("emailFromName"))), refVal_setEmailFromName );
        setEmailFromName(refVal_setEmailFromName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("emailFromEmail"))))
    {
        utility::string_t refVal_setEmailFromEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("emailFromEmail"))), refVal_setEmailFromEmail );
        setEmailFromEmail(refVal_setEmailFromEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("emailHeaders"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setEmailHeaders;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("emailHeaders"))), refVal_setEmailHeaders );
        setEmailHeaders(refVal_setEmailHeaders);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("wpSyncToken"))))
    {
        utility::string_t refVal_setWpSyncToken;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("wpSyncToken"))), refVal_setWpSyncToken );
        setWpSyncToken(refVal_setWpSyncToken);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("wpSynced"))))
    {
        bool refVal_setWpSynced;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("wpSynced"))), refVal_setWpSynced );
        setWpSynced(refVal_setWpSynced);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("wpURL"))))
    {
        utility::string_t refVal_setWpURL;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("wpURL"))), refVal_setWpURL );
        setWpURL(refVal_setWpURL);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("autoAddedDate"))))
    {
        utility::datetime refVal_setAutoAddedDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("autoAddedDate"))), refVal_setAutoAddedDate );
        setAutoAddedDate(refVal_setAutoAddedDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("siteType"))))
    {
        std::shared_ptr<ImportedSiteType> refVal_setSiteType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("siteType"))), refVal_setSiteType );
        setSiteType(refVal_setSiteType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("logoSrc"))))
    {
        utility::string_t refVal_setLogoSrc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("logoSrc"))), refVal_setLogoSrc );
        setLogoSrc(refVal_setLogoSrc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("logoSrc100px"))))
    {
        utility::string_t refVal_setLogoSrc100px;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("logoSrc100px"))), refVal_setLogoSrc100px );
        setLogoSrc100px(refVal_setLogoSrc100px);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("footerUnsubscribeURL"))))
    {
        utility::string_t refVal_setFooterUnsubscribeURL;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("footerUnsubscribeURL"))), refVal_setFooterUnsubscribeURL );
        setFooterUnsubscribeURL(refVal_setFooterUnsubscribeURL);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("disableUnsubscribeLinks"))))
    {
        bool refVal_setDisableUnsubscribeLinks;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("disableUnsubscribeLinks"))), refVal_setDisableUnsubscribeLinks );
        setDisableUnsubscribeLinks(refVal_setDisableUnsubscribeLinks);
    }
    return ok;
}


utility::string_t APIDomainConfiguration::getId() const
{
    return m_Id;
}


void APIDomainConfiguration::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool APIDomainConfiguration::idIsSet() const
{
    return m_IdIsSet;
}

void APIDomainConfiguration::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t APIDomainConfiguration::getDomain() const
{
    return m_Domain;
}


void APIDomainConfiguration::setDomain(const utility::string_t& value)
{
    m_Domain = value;
    m_DomainIsSet = true;
}

bool APIDomainConfiguration::domainIsSet() const
{
    return m_DomainIsSet;
}

void APIDomainConfiguration::unsetDomain()
{
    m_DomainIsSet = false;
}
utility::string_t APIDomainConfiguration::getEmailFromName() const
{
    return m_EmailFromName;
}


void APIDomainConfiguration::setEmailFromName(const utility::string_t& value)
{
    m_EmailFromName = value;
    m_EmailFromNameIsSet = true;
}

bool APIDomainConfiguration::emailFromNameIsSet() const
{
    return m_EmailFromNameIsSet;
}

void APIDomainConfiguration::unsetEmailFromName()
{
    m_EmailFromNameIsSet = false;
}
utility::string_t APIDomainConfiguration::getEmailFromEmail() const
{
    return m_EmailFromEmail;
}


void APIDomainConfiguration::setEmailFromEmail(const utility::string_t& value)
{
    m_EmailFromEmail = value;
    m_EmailFromEmailIsSet = true;
}

bool APIDomainConfiguration::emailFromEmailIsSet() const
{
    return m_EmailFromEmailIsSet;
}

void APIDomainConfiguration::unsetEmailFromEmail()
{
    m_EmailFromEmailIsSet = false;
}
std::map<utility::string_t, utility::string_t> APIDomainConfiguration::getEmailHeaders() const
{
    return m_EmailHeaders;
}


void APIDomainConfiguration::setEmailHeaders(const std::map<utility::string_t, utility::string_t>& value)
{
    m_EmailHeaders = value;
    m_EmailHeadersIsSet = true;
}

bool APIDomainConfiguration::emailHeadersIsSet() const
{
    return m_EmailHeadersIsSet;
}

void APIDomainConfiguration::unsetEmailHeaders()
{
    m_EmailHeadersIsSet = false;
}
utility::string_t APIDomainConfiguration::getWpSyncToken() const
{
    return m_WpSyncToken;
}


void APIDomainConfiguration::setWpSyncToken(const utility::string_t& value)
{
    m_WpSyncToken = value;
    m_WpSyncTokenIsSet = true;
}

bool APIDomainConfiguration::wpSyncTokenIsSet() const
{
    return m_WpSyncTokenIsSet;
}

void APIDomainConfiguration::unsetWpSyncToken()
{
    m_WpSyncTokenIsSet = false;
}
bool APIDomainConfiguration::isWpSynced() const
{
    return m_WpSynced;
}

void APIDomainConfiguration::setWpSynced(bool value)
{
    m_WpSynced = value;
    m_WpSyncedIsSet = true;
}

bool APIDomainConfiguration::wpSyncedIsSet() const
{
    return m_WpSyncedIsSet;
}

void APIDomainConfiguration::unsetWpSynced()
{
    m_WpSyncedIsSet = false;
}
utility::string_t APIDomainConfiguration::getWpURL() const
{
    return m_WpURL;
}


void APIDomainConfiguration::setWpURL(const utility::string_t& value)
{
    m_WpURL = value;
    m_WpURLIsSet = true;
}

bool APIDomainConfiguration::wpURLIsSet() const
{
    return m_WpURLIsSet;
}

void APIDomainConfiguration::unsetWpURL()
{
    m_WpURLIsSet = false;
}
utility::datetime APIDomainConfiguration::getCreatedAt() const
{
    return m_CreatedAt;
}


void APIDomainConfiguration::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool APIDomainConfiguration::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void APIDomainConfiguration::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
utility::datetime APIDomainConfiguration::getAutoAddedDate() const
{
    return m_AutoAddedDate;
}


void APIDomainConfiguration::setAutoAddedDate(const utility::datetime& value)
{
    m_AutoAddedDate = value;
    m_AutoAddedDateIsSet = true;
}

bool APIDomainConfiguration::autoAddedDateIsSet() const
{
    return m_AutoAddedDateIsSet;
}

void APIDomainConfiguration::unsetAutoAddedDate()
{
    m_AutoAddedDateIsSet = false;
}
std::shared_ptr<ImportedSiteType> APIDomainConfiguration::getSiteType() const
{
    return m_SiteType;
}


void APIDomainConfiguration::setSiteType(const std::shared_ptr<ImportedSiteType>& value)
{
    m_SiteType = value;
    m_SiteTypeIsSet = true;
}

bool APIDomainConfiguration::siteTypeIsSet() const
{
    return m_SiteTypeIsSet;
}

void APIDomainConfiguration::unsetSiteType()
{
    m_SiteTypeIsSet = false;
}
utility::string_t APIDomainConfiguration::getLogoSrc() const
{
    return m_LogoSrc;
}


void APIDomainConfiguration::setLogoSrc(const utility::string_t& value)
{
    m_LogoSrc = value;
    m_LogoSrcIsSet = true;
}

bool APIDomainConfiguration::logoSrcIsSet() const
{
    return m_LogoSrcIsSet;
}

void APIDomainConfiguration::unsetLogoSrc()
{
    m_LogoSrcIsSet = false;
}
utility::string_t APIDomainConfiguration::getLogoSrc100px() const
{
    return m_LogoSrc100px;
}


void APIDomainConfiguration::setLogoSrc100px(const utility::string_t& value)
{
    m_LogoSrc100px = value;
    m_LogoSrc100pxIsSet = true;
}

bool APIDomainConfiguration::logoSrc100pxIsSet() const
{
    return m_LogoSrc100pxIsSet;
}

void APIDomainConfiguration::unsetLogoSrc100px()
{
    m_LogoSrc100pxIsSet = false;
}
utility::string_t APIDomainConfiguration::getFooterUnsubscribeURL() const
{
    return m_FooterUnsubscribeURL;
}


void APIDomainConfiguration::setFooterUnsubscribeURL(const utility::string_t& value)
{
    m_FooterUnsubscribeURL = value;
    m_FooterUnsubscribeURLIsSet = true;
}

bool APIDomainConfiguration::footerUnsubscribeURLIsSet() const
{
    return m_FooterUnsubscribeURLIsSet;
}

void APIDomainConfiguration::unsetFooterUnsubscribeURL()
{
    m_FooterUnsubscribeURLIsSet = false;
}
bool APIDomainConfiguration::isDisableUnsubscribeLinks() const
{
    return m_DisableUnsubscribeLinks;
}

void APIDomainConfiguration::setDisableUnsubscribeLinks(bool value)
{
    m_DisableUnsubscribeLinks = value;
    m_DisableUnsubscribeLinksIsSet = true;
}

bool APIDomainConfiguration::disableUnsubscribeLinksIsSet() const
{
    return m_DisableUnsubscribeLinksIsSet;
}

void APIDomainConfiguration::unsetDisableUnsubscribeLinks()
{
    m_DisableUnsubscribeLinksIsSet = false;
}

}
}
}
}


