/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/APIStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

APIStatus::eAPIStatus toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("success")))
        return APIStatus::eAPIStatus::SUCCESS;
    if (val == utility::conversions::to_string_t(_XPLATSTR("failed")))
        return APIStatus::eAPIStatus::FAILED;
    return {};
}

EnumUnderlyingType fromEnum(APIStatus::eAPIStatus e)
{
    switch (e)
    {
    case APIStatus::eAPIStatus::SUCCESS:
        return _XPLATSTR("success");
    case APIStatus::eAPIStatus::FAILED:
        return _XPLATSTR("failed");
    default:
        break;
    }
    return {};
}
}

APIStatus::APIStatus()
{
}

APIStatus::~APIStatus()
{
}

void APIStatus::validate()
{
    // TODO: implement validation
}

web::json::value APIStatus::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool APIStatus::fromJson(const web::json::value& val)
{
    if (!val.is_string()) {
        return false;
    }
    m_value = toEnum(val.as_string());
    return true;
}

void APIStatus::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool APIStatus::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

APIStatus::eAPIStatus APIStatus::getValue() const
{
   return m_value;
}

void APIStatus::setValue(APIStatus::eAPIStatus const value)
{
   m_value = value;
}

APIStatus::APIStatus(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


