/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/APISSOUser.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

APISSOUser::APISSOUser()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Username = utility::conversions::to_string_t("");
    m_UsernameIsSet = false;
    m_WebsiteUrl = utility::conversions::to_string_t("");
    m_WebsiteUrlIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_SignUpDate = 0L;
    m_SignUpDateIsSet = false;
    m_CreatedFromUrlId = utility::conversions::to_string_t("");
    m_CreatedFromUrlIdIsSet = false;
    m_LoginCount = 0;
    m_LoginCountIsSet = false;
    m_AvatarSrc = utility::conversions::to_string_t("");
    m_AvatarSrcIsSet = false;
    m_OptedInNotifications = false;
    m_OptedInNotificationsIsSet = false;
    m_OptedInSubscriptionNotifications = false;
    m_OptedInSubscriptionNotificationsIsSet = false;
    m_DisplayLabel = utility::conversions::to_string_t("");
    m_DisplayLabelIsSet = false;
    m_DisplayName = utility::conversions::to_string_t("");
    m_DisplayNameIsSet = false;
    m_IsAccountOwner = false;
    m_IsAccountOwnerIsSet = false;
    m_IsAdminAdmin = false;
    m_IsAdminAdminIsSet = false;
    m_IsCommentModeratorAdmin = false;
    m_IsCommentModeratorAdminIsSet = false;
    m_IsProfileActivityPrivate = false;
    m_IsProfileActivityPrivateIsSet = false;
    m_IsProfileCommentsPrivate = false;
    m_IsProfileCommentsPrivateIsSet = false;
    m_IsProfileDMDisabled = false;
    m_IsProfileDMDisabledIsSet = false;
    m_HasBlockedUsers = false;
    m_HasBlockedUsersIsSet = false;
    m_GroupIdsIsSet = false;
}

APISSOUser::~APISSOUser()
{
}

void APISSOUser::validate()
{
    // TODO: implement validation
}

web::json::value APISSOUser::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_UsernameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("username"))] = ModelBase::toJson(m_Username);
    }
    if(m_WebsiteUrlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("websiteUrl"))] = ModelBase::toJson(m_WebsiteUrl);
    }
    if(m_EmailIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_SignUpDateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("signUpDate"))] = ModelBase::toJson(m_SignUpDate);
    }
    if(m_CreatedFromUrlIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdFromUrlId"))] = ModelBase::toJson(m_CreatedFromUrlId);
    }
    if(m_LoginCountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("loginCount"))] = ModelBase::toJson(m_LoginCount);
    }
    if(m_AvatarSrcIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("avatarSrc"))] = ModelBase::toJson(m_AvatarSrc);
    }
    if(m_OptedInNotificationsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("optedInNotifications"))] = ModelBase::toJson(m_OptedInNotifications);
    }
    if(m_OptedInSubscriptionNotificationsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("optedInSubscriptionNotifications"))] = ModelBase::toJson(m_OptedInSubscriptionNotifications);
    }
    if(m_DisplayLabelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("displayLabel"))] = ModelBase::toJson(m_DisplayLabel);
    }
    if(m_DisplayNameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("displayName"))] = ModelBase::toJson(m_DisplayName);
    }
    if(m_IsAccountOwnerIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isAccountOwner"))] = ModelBase::toJson(m_IsAccountOwner);
    }
    if(m_IsAdminAdminIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isAdminAdmin"))] = ModelBase::toJson(m_IsAdminAdmin);
    }
    if(m_IsCommentModeratorAdminIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isCommentModeratorAdmin"))] = ModelBase::toJson(m_IsCommentModeratorAdmin);
    }
    if(m_IsProfileActivityPrivateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isProfileActivityPrivate"))] = ModelBase::toJson(m_IsProfileActivityPrivate);
    }
    if(m_IsProfileCommentsPrivateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isProfileCommentsPrivate"))] = ModelBase::toJson(m_IsProfileCommentsPrivate);
    }
    if(m_IsProfileDMDisabledIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isProfileDMDisabled"))] = ModelBase::toJson(m_IsProfileDMDisabled);
    }
    if(m_HasBlockedUsersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("hasBlockedUsers"))] = ModelBase::toJson(m_HasBlockedUsers);
    }
    if(m_GroupIdsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("groupIds"))] = ModelBase::toJson(m_GroupIds);
    }

    return val;
}

bool APISSOUser::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("username"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("username")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUsername;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUsername);
            setUsername(refVal_setUsername);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("websiteUrl"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("websiteUrl")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWebsiteUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWebsiteUrl);
            setWebsiteUrl(refVal_setWebsiteUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("signUpDate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("signUpDate")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setSignUpDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSignUpDate);
            setSignUpDate(refVal_setSignUpDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdFromUrlId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdFromUrlId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedFromUrlId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedFromUrlId);
            setCreatedFromUrlId(refVal_setCreatedFromUrlId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("loginCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("loginCount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLoginCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLoginCount);
            setLoginCount(refVal_setLoginCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("avatarSrc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("avatarSrc")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatarSrc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatarSrc);
            setAvatarSrc(refVal_setAvatarSrc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("optedInNotifications"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("optedInNotifications")));
        if(!fieldValue.is_null())
        {
            bool refVal_setOptedInNotifications;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOptedInNotifications);
            setOptedInNotifications(refVal_setOptedInNotifications);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("optedInSubscriptionNotifications"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("optedInSubscriptionNotifications")));
        if(!fieldValue.is_null())
        {
            bool refVal_setOptedInSubscriptionNotifications;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOptedInSubscriptionNotifications);
            setOptedInSubscriptionNotifications(refVal_setOptedInSubscriptionNotifications);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("displayLabel"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("displayLabel")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDisplayLabel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDisplayLabel);
            setDisplayLabel(refVal_setDisplayLabel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("displayName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("displayName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDisplayName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDisplayName);
            setDisplayName(refVal_setDisplayName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isAccountOwner"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isAccountOwner")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsAccountOwner;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsAccountOwner);
            setIsAccountOwner(refVal_setIsAccountOwner);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isAdminAdmin"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isAdminAdmin")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsAdminAdmin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsAdminAdmin);
            setIsAdminAdmin(refVal_setIsAdminAdmin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isCommentModeratorAdmin"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isCommentModeratorAdmin")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsCommentModeratorAdmin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsCommentModeratorAdmin);
            setIsCommentModeratorAdmin(refVal_setIsCommentModeratorAdmin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isProfileActivityPrivate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isProfileActivityPrivate")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsProfileActivityPrivate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsProfileActivityPrivate);
            setIsProfileActivityPrivate(refVal_setIsProfileActivityPrivate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isProfileCommentsPrivate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isProfileCommentsPrivate")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsProfileCommentsPrivate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsProfileCommentsPrivate);
            setIsProfileCommentsPrivate(refVal_setIsProfileCommentsPrivate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isProfileDMDisabled"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isProfileDMDisabled")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsProfileDMDisabled;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsProfileDMDisabled);
            setIsProfileDMDisabled(refVal_setIsProfileDMDisabled);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("hasBlockedUsers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("hasBlockedUsers")));
        if(!fieldValue.is_null())
        {
            bool refVal_setHasBlockedUsers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHasBlockedUsers);
            setHasBlockedUsers(refVal_setHasBlockedUsers);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("groupIds"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("groupIds")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setGroupIds;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGroupIds);
            setGroupIds(refVal_setGroupIds);
            
        }
    }
    return ok;
}

void APISSOUser::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_UsernameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("username")), m_Username));
    }
    if(m_WebsiteUrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("websiteUrl")), m_WebsiteUrl));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_SignUpDateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("signUpDate")), m_SignUpDate));
    }
    if(m_CreatedFromUrlIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdFromUrlId")), m_CreatedFromUrlId));
    }
    if(m_LoginCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("loginCount")), m_LoginCount));
    }
    if(m_AvatarSrcIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("avatarSrc")), m_AvatarSrc));
    }
    if(m_OptedInNotificationsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("optedInNotifications")), m_OptedInNotifications));
    }
    if(m_OptedInSubscriptionNotificationsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("optedInSubscriptionNotifications")), m_OptedInSubscriptionNotifications));
    }
    if(m_DisplayLabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("displayLabel")), m_DisplayLabel));
    }
    if(m_DisplayNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("displayName")), m_DisplayName));
    }
    if(m_IsAccountOwnerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isAccountOwner")), m_IsAccountOwner));
    }
    if(m_IsAdminAdminIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isAdminAdmin")), m_IsAdminAdmin));
    }
    if(m_IsCommentModeratorAdminIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isCommentModeratorAdmin")), m_IsCommentModeratorAdmin));
    }
    if(m_IsProfileActivityPrivateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isProfileActivityPrivate")), m_IsProfileActivityPrivate));
    }
    if(m_IsProfileCommentsPrivateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isProfileCommentsPrivate")), m_IsProfileCommentsPrivate));
    }
    if(m_IsProfileDMDisabledIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isProfileDMDisabled")), m_IsProfileDMDisabled));
    }
    if(m_HasBlockedUsersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("hasBlockedUsers")), m_HasBlockedUsers));
    }
    if(m_GroupIdsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("groupIds")), m_GroupIds));
    }
}

bool APISSOUser::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("username"))))
    {
        utility::string_t refVal_setUsername;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("username"))), refVal_setUsername );
        setUsername(refVal_setUsername);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("websiteUrl"))))
    {
        utility::string_t refVal_setWebsiteUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("websiteUrl"))), refVal_setWebsiteUrl );
        setWebsiteUrl(refVal_setWebsiteUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("signUpDate"))))
    {
        int64_t refVal_setSignUpDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("signUpDate"))), refVal_setSignUpDate );
        setSignUpDate(refVal_setSignUpDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdFromUrlId"))))
    {
        utility::string_t refVal_setCreatedFromUrlId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdFromUrlId"))), refVal_setCreatedFromUrlId );
        setCreatedFromUrlId(refVal_setCreatedFromUrlId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("loginCount"))))
    {
        int32_t refVal_setLoginCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("loginCount"))), refVal_setLoginCount );
        setLoginCount(refVal_setLoginCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("avatarSrc"))))
    {
        utility::string_t refVal_setAvatarSrc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("avatarSrc"))), refVal_setAvatarSrc );
        setAvatarSrc(refVal_setAvatarSrc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("optedInNotifications"))))
    {
        bool refVal_setOptedInNotifications;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("optedInNotifications"))), refVal_setOptedInNotifications );
        setOptedInNotifications(refVal_setOptedInNotifications);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("optedInSubscriptionNotifications"))))
    {
        bool refVal_setOptedInSubscriptionNotifications;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("optedInSubscriptionNotifications"))), refVal_setOptedInSubscriptionNotifications );
        setOptedInSubscriptionNotifications(refVal_setOptedInSubscriptionNotifications);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("displayLabel"))))
    {
        utility::string_t refVal_setDisplayLabel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("displayLabel"))), refVal_setDisplayLabel );
        setDisplayLabel(refVal_setDisplayLabel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("displayName"))))
    {
        utility::string_t refVal_setDisplayName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("displayName"))), refVal_setDisplayName );
        setDisplayName(refVal_setDisplayName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isAccountOwner"))))
    {
        bool refVal_setIsAccountOwner;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isAccountOwner"))), refVal_setIsAccountOwner );
        setIsAccountOwner(refVal_setIsAccountOwner);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isAdminAdmin"))))
    {
        bool refVal_setIsAdminAdmin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isAdminAdmin"))), refVal_setIsAdminAdmin );
        setIsAdminAdmin(refVal_setIsAdminAdmin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isCommentModeratorAdmin"))))
    {
        bool refVal_setIsCommentModeratorAdmin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isCommentModeratorAdmin"))), refVal_setIsCommentModeratorAdmin );
        setIsCommentModeratorAdmin(refVal_setIsCommentModeratorAdmin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isProfileActivityPrivate"))))
    {
        bool refVal_setIsProfileActivityPrivate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isProfileActivityPrivate"))), refVal_setIsProfileActivityPrivate );
        setIsProfileActivityPrivate(refVal_setIsProfileActivityPrivate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isProfileCommentsPrivate"))))
    {
        bool refVal_setIsProfileCommentsPrivate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isProfileCommentsPrivate"))), refVal_setIsProfileCommentsPrivate );
        setIsProfileCommentsPrivate(refVal_setIsProfileCommentsPrivate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isProfileDMDisabled"))))
    {
        bool refVal_setIsProfileDMDisabled;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isProfileDMDisabled"))), refVal_setIsProfileDMDisabled );
        setIsProfileDMDisabled(refVal_setIsProfileDMDisabled);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("hasBlockedUsers"))))
    {
        bool refVal_setHasBlockedUsers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("hasBlockedUsers"))), refVal_setHasBlockedUsers );
        setHasBlockedUsers(refVal_setHasBlockedUsers);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("groupIds"))))
    {
        std::vector<utility::string_t> refVal_setGroupIds;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("groupIds"))), refVal_setGroupIds );
        setGroupIds(refVal_setGroupIds);
    }
    return ok;
}


utility::string_t APISSOUser::getId() const
{
    return m_Id;
}


void APISSOUser::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool APISSOUser::idIsSet() const
{
    return m_IdIsSet;
}

void APISSOUser::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t APISSOUser::getUsername() const
{
    return m_Username;
}


void APISSOUser::setUsername(const utility::string_t& value)
{
    m_Username = value;
    m_UsernameIsSet = true;
}

bool APISSOUser::usernameIsSet() const
{
    return m_UsernameIsSet;
}

void APISSOUser::unsetUsername()
{
    m_UsernameIsSet = false;
}
utility::string_t APISSOUser::getWebsiteUrl() const
{
    return m_WebsiteUrl;
}


void APISSOUser::setWebsiteUrl(const utility::string_t& value)
{
    m_WebsiteUrl = value;
    m_WebsiteUrlIsSet = true;
}

bool APISSOUser::websiteUrlIsSet() const
{
    return m_WebsiteUrlIsSet;
}

void APISSOUser::unsetWebsiteUrl()
{
    m_WebsiteUrlIsSet = false;
}
utility::string_t APISSOUser::getEmail() const
{
    return m_Email;
}


void APISSOUser::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool APISSOUser::emailIsSet() const
{
    return m_EmailIsSet;
}

void APISSOUser::unsetEmail()
{
    m_EmailIsSet = false;
}
int64_t APISSOUser::getSignUpDate() const
{
    return m_SignUpDate;
}

void APISSOUser::setSignUpDate(int64_t value)
{
    m_SignUpDate = value;
    m_SignUpDateIsSet = true;
}

bool APISSOUser::signUpDateIsSet() const
{
    return m_SignUpDateIsSet;
}

void APISSOUser::unsetSignUpDate()
{
    m_SignUpDateIsSet = false;
}
utility::string_t APISSOUser::getCreatedFromUrlId() const
{
    return m_CreatedFromUrlId;
}


void APISSOUser::setCreatedFromUrlId(const utility::string_t& value)
{
    m_CreatedFromUrlId = value;
    m_CreatedFromUrlIdIsSet = true;
}

bool APISSOUser::createdFromUrlIdIsSet() const
{
    return m_CreatedFromUrlIdIsSet;
}

void APISSOUser::unsetCreatedFromUrlId()
{
    m_CreatedFromUrlIdIsSet = false;
}
int32_t APISSOUser::getLoginCount() const
{
    return m_LoginCount;
}

void APISSOUser::setLoginCount(int32_t value)
{
    m_LoginCount = value;
    m_LoginCountIsSet = true;
}

bool APISSOUser::loginCountIsSet() const
{
    return m_LoginCountIsSet;
}

void APISSOUser::unsetLoginCount()
{
    m_LoginCountIsSet = false;
}
utility::string_t APISSOUser::getAvatarSrc() const
{
    return m_AvatarSrc;
}


void APISSOUser::setAvatarSrc(const utility::string_t& value)
{
    m_AvatarSrc = value;
    m_AvatarSrcIsSet = true;
}

bool APISSOUser::avatarSrcIsSet() const
{
    return m_AvatarSrcIsSet;
}

void APISSOUser::unsetAvatarSrc()
{
    m_AvatarSrcIsSet = false;
}
bool APISSOUser::isOptedInNotifications() const
{
    return m_OptedInNotifications;
}

void APISSOUser::setOptedInNotifications(bool value)
{
    m_OptedInNotifications = value;
    m_OptedInNotificationsIsSet = true;
}

bool APISSOUser::optedInNotificationsIsSet() const
{
    return m_OptedInNotificationsIsSet;
}

void APISSOUser::unsetOptedInNotifications()
{
    m_OptedInNotificationsIsSet = false;
}
bool APISSOUser::isOptedInSubscriptionNotifications() const
{
    return m_OptedInSubscriptionNotifications;
}

void APISSOUser::setOptedInSubscriptionNotifications(bool value)
{
    m_OptedInSubscriptionNotifications = value;
    m_OptedInSubscriptionNotificationsIsSet = true;
}

bool APISSOUser::optedInSubscriptionNotificationsIsSet() const
{
    return m_OptedInSubscriptionNotificationsIsSet;
}

void APISSOUser::unsetOptedInSubscriptionNotifications()
{
    m_OptedInSubscriptionNotificationsIsSet = false;
}
utility::string_t APISSOUser::getDisplayLabel() const
{
    return m_DisplayLabel;
}


void APISSOUser::setDisplayLabel(const utility::string_t& value)
{
    m_DisplayLabel = value;
    m_DisplayLabelIsSet = true;
}

bool APISSOUser::displayLabelIsSet() const
{
    return m_DisplayLabelIsSet;
}

void APISSOUser::unsetDisplayLabel()
{
    m_DisplayLabelIsSet = false;
}
utility::string_t APISSOUser::getDisplayName() const
{
    return m_DisplayName;
}


void APISSOUser::setDisplayName(const utility::string_t& value)
{
    m_DisplayName = value;
    m_DisplayNameIsSet = true;
}

bool APISSOUser::displayNameIsSet() const
{
    return m_DisplayNameIsSet;
}

void APISSOUser::unsetDisplayName()
{
    m_DisplayNameIsSet = false;
}
bool APISSOUser::isIsAccountOwner() const
{
    return m_IsAccountOwner;
}

void APISSOUser::setIsAccountOwner(bool value)
{
    m_IsAccountOwner = value;
    m_IsAccountOwnerIsSet = true;
}

bool APISSOUser::isAccountOwnerIsSet() const
{
    return m_IsAccountOwnerIsSet;
}

void APISSOUser::unsetIsAccountOwner()
{
    m_IsAccountOwnerIsSet = false;
}
bool APISSOUser::isIsAdminAdmin() const
{
    return m_IsAdminAdmin;
}

void APISSOUser::setIsAdminAdmin(bool value)
{
    m_IsAdminAdmin = value;
    m_IsAdminAdminIsSet = true;
}

bool APISSOUser::isAdminAdminIsSet() const
{
    return m_IsAdminAdminIsSet;
}

void APISSOUser::unsetIsAdminAdmin()
{
    m_IsAdminAdminIsSet = false;
}
bool APISSOUser::isIsCommentModeratorAdmin() const
{
    return m_IsCommentModeratorAdmin;
}

void APISSOUser::setIsCommentModeratorAdmin(bool value)
{
    m_IsCommentModeratorAdmin = value;
    m_IsCommentModeratorAdminIsSet = true;
}

bool APISSOUser::isCommentModeratorAdminIsSet() const
{
    return m_IsCommentModeratorAdminIsSet;
}

void APISSOUser::unsetIsCommentModeratorAdmin()
{
    m_IsCommentModeratorAdminIsSet = false;
}
bool APISSOUser::isIsProfileActivityPrivate() const
{
    return m_IsProfileActivityPrivate;
}

void APISSOUser::setIsProfileActivityPrivate(bool value)
{
    m_IsProfileActivityPrivate = value;
    m_IsProfileActivityPrivateIsSet = true;
}

bool APISSOUser::isProfileActivityPrivateIsSet() const
{
    return m_IsProfileActivityPrivateIsSet;
}

void APISSOUser::unsetIsProfileActivityPrivate()
{
    m_IsProfileActivityPrivateIsSet = false;
}
bool APISSOUser::isIsProfileCommentsPrivate() const
{
    return m_IsProfileCommentsPrivate;
}

void APISSOUser::setIsProfileCommentsPrivate(bool value)
{
    m_IsProfileCommentsPrivate = value;
    m_IsProfileCommentsPrivateIsSet = true;
}

bool APISSOUser::isProfileCommentsPrivateIsSet() const
{
    return m_IsProfileCommentsPrivateIsSet;
}

void APISSOUser::unsetIsProfileCommentsPrivate()
{
    m_IsProfileCommentsPrivateIsSet = false;
}
bool APISSOUser::isIsProfileDMDisabled() const
{
    return m_IsProfileDMDisabled;
}

void APISSOUser::setIsProfileDMDisabled(bool value)
{
    m_IsProfileDMDisabled = value;
    m_IsProfileDMDisabledIsSet = true;
}

bool APISSOUser::isProfileDMDisabledIsSet() const
{
    return m_IsProfileDMDisabledIsSet;
}

void APISSOUser::unsetIsProfileDMDisabled()
{
    m_IsProfileDMDisabledIsSet = false;
}
bool APISSOUser::isHasBlockedUsers() const
{
    return m_HasBlockedUsers;
}

void APISSOUser::setHasBlockedUsers(bool value)
{
    m_HasBlockedUsers = value;
    m_HasBlockedUsersIsSet = true;
}

bool APISSOUser::hasBlockedUsersIsSet() const
{
    return m_HasBlockedUsersIsSet;
}

void APISSOUser::unsetHasBlockedUsers()
{
    m_HasBlockedUsersIsSet = false;
}
std::vector<utility::string_t> APISSOUser::getGroupIds() const
{
    return m_GroupIds;
}


void APISSOUser::setGroupIds(const std::vector<utility::string_t>& value)
{
    m_GroupIds = value;
    m_GroupIdsIsSet = true;
}

bool APISSOUser::groupIdsIsSet() const
{
    return m_GroupIdsIsSet;
}

void APISSOUser::unsetGroupIds()
{
    m_GroupIdsIsSet = false;
}

}
}
}
}


