/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/APITicketDetail.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

APITicketDetail::APITicketDetail()
{
    m__id = utility::conversions::to_string_t("");
    m__idIsSet = false;
    m_UrlId = utility::conversions::to_string_t("");
    m_UrlIdIsSet = false;
    m_UserId = utility::conversions::to_string_t("");
    m_UserIdIsSet = false;
    m_ManagedByTenantId = utility::conversions::to_string_t("");
    m_ManagedByTenantIdIsSet = false;
    m_AssignedUserIdsIsSet = false;
    m_Subject = utility::conversions::to_string_t("");
    m_SubjectIsSet = false;
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_State = 0;
    m_StateIsSet = false;
    m_FileCount = 0;
    m_FileCountIsSet = false;
    m_FilesIsSet = false;
}

APITicketDetail::~APITicketDetail()
{
}

void APITicketDetail::validate()
{
    // TODO: implement validation
}

web::json::value APITicketDetail::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m__idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("_id"))] = ModelBase::toJson(m__id);
    }
    if(m_UrlIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("urlId"))] = ModelBase::toJson(m_UrlId);
    }
    if(m_UserIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("userId"))] = ModelBase::toJson(m_UserId);
    }
    if(m_ManagedByTenantIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("managedByTenantId"))] = ModelBase::toJson(m_ManagedByTenantId);
    }
    if(m_AssignedUserIdsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("assignedUserIds"))] = ModelBase::toJson(m_AssignedUserIds);
    }
    if(m_SubjectIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subject"))] = ModelBase::toJson(m_Subject);
    }
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_StateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("state"))] = ModelBase::toJson(m_State);
    }
    if(m_FileCountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fileCount"))] = ModelBase::toJson(m_FileCount);
    }
    if(m_FilesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("files"))] = ModelBase::toJson(m_Files);
    }
    if(m_ReopenedAt.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("reopenedAt"))] = ModelBase::toJson(m_ReopenedAt.get());
    }
    if(m_ResolvedAt.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("resolvedAt"))] = ModelBase::toJson(m_ResolvedAt.get());
    }
    if(m_AckAt.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("ackAt"))] = ModelBase::toJson(m_AckAt.get());
    }

    return val;
}

bool APITicketDetail::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("urlId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("urlId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrlId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrlId);
            setUrlId(refVal_setUrlId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserId);
            setUserId(refVal_setUserId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("managedByTenantId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("managedByTenantId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setManagedByTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManagedByTenantId);
            setManagedByTenantId(refVal_setManagedByTenantId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("assignedUserIds"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("assignedUserIds")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setAssignedUserIds;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAssignedUserIds);
            setAssignedUserIds(refVal_setAssignedUserIds);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subject")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubject);
            setSubject(refVal_setSubject);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("state")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setState;
            ok &= ModelBase::fromJson(fieldValue, refVal_setState);
            setState(refVal_setState);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fileCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fileCount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFileCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFileCount);
            setFileCount(refVal_setFileCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("files"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("files")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<APITicketFile>> refVal_setFiles;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFiles);
            setFiles(refVal_setFiles);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reopenedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reopenedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setReopenedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReopenedAt);
            setReopenedAt(refVal_setReopenedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("resolvedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("resolvedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setResolvedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResolvedAt);
            setResolvedAt(refVal_setResolvedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ackAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ackAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAckAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAckAt);
            setAckAt(refVal_setAckAt);
            
        }
    }
    return ok;
}

void APITicketDetail::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m__idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("_id")), m__id));
    }
    if(m_UrlIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("urlId")), m_UrlId));
    }
    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userId")), m_UserId));
    }
    if(m_ManagedByTenantIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("managedByTenantId")), m_ManagedByTenantId));
    }
    if(m_AssignedUserIdsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("assignedUserIds")), m_AssignedUserIds));
    }
    if(m_SubjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subject")), m_Subject));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_StateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("state")), m_State));
    }
    if(m_FileCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fileCount")), m_FileCount));
    }
    if(m_FilesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("files")), m_Files));
    }
    if(m_ReopenedAt.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reopenedAt")), m_ReopenedAt.get()));
    }
    if(m_ResolvedAt.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("resolvedAt")), m_ResolvedAt.get()));
    }
    if(m_AckAt.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ackAt")), m_AckAt.get()));
    }
}

bool APITicketDetail::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("_id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("urlId"))))
    {
        utility::string_t refVal_setUrlId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("urlId"))), refVal_setUrlId );
        setUrlId(refVal_setUrlId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        utility::string_t refVal_setUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userId"))), refVal_setUserId );
        setUserId(refVal_setUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("managedByTenantId"))))
    {
        utility::string_t refVal_setManagedByTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("managedByTenantId"))), refVal_setManagedByTenantId );
        setManagedByTenantId(refVal_setManagedByTenantId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("assignedUserIds"))))
    {
        std::vector<utility::string_t> refVal_setAssignedUserIds;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("assignedUserIds"))), refVal_setAssignedUserIds );
        setAssignedUserIds(refVal_setAssignedUserIds);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        utility::string_t refVal_setSubject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subject"))), refVal_setSubject );
        setSubject(refVal_setSubject);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        int32_t refVal_setState;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("state"))), refVal_setState );
        setState(refVal_setState);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fileCount"))))
    {
        int32_t refVal_setFileCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fileCount"))), refVal_setFileCount );
        setFileCount(refVal_setFileCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("files"))))
    {
        std::vector<std::shared_ptr<APITicketFile>> refVal_setFiles;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("files"))), refVal_setFiles );
        setFiles(refVal_setFiles);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reopenedAt"))))
    {
        utility::string_t refVal_setReopenedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reopenedAt"))), refVal_setReopenedAt );
        setReopenedAt(refVal_setReopenedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("resolvedAt"))))
    {
        utility::string_t refVal_setResolvedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("resolvedAt"))), refVal_setResolvedAt );
        setResolvedAt(refVal_setResolvedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ackAt"))))
    {
        utility::string_t refVal_setAckAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ackAt"))), refVal_setAckAt );
        setAckAt(refVal_setAckAt);
    }
    return ok;
}


utility::string_t APITicketDetail::getId() const
{
    return m__id;
}


void APITicketDetail::setId(const utility::string_t& value)
{
    m__id = value;
    m__idIsSet = true;
}

bool APITicketDetail::idIsSet() const
{
    return m__idIsSet;
}

void APITicketDetail::unset_id()
{
    m__idIsSet = false;
}
utility::string_t APITicketDetail::getUrlId() const
{
    return m_UrlId;
}


void APITicketDetail::setUrlId(const utility::string_t& value)
{
    m_UrlId = value;
    m_UrlIdIsSet = true;
}

bool APITicketDetail::urlIdIsSet() const
{
    return m_UrlIdIsSet;
}

void APITicketDetail::unsetUrlId()
{
    m_UrlIdIsSet = false;
}
utility::string_t APITicketDetail::getUserId() const
{
    return m_UserId;
}


void APITicketDetail::setUserId(const utility::string_t& value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}

bool APITicketDetail::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void APITicketDetail::unsetUserId()
{
    m_UserIdIsSet = false;
}
utility::string_t APITicketDetail::getManagedByTenantId() const
{
    return m_ManagedByTenantId;
}


void APITicketDetail::setManagedByTenantId(const utility::string_t& value)
{
    m_ManagedByTenantId = value;
    m_ManagedByTenantIdIsSet = true;
}

bool APITicketDetail::managedByTenantIdIsSet() const
{
    return m_ManagedByTenantIdIsSet;
}

void APITicketDetail::unsetManagedByTenantId()
{
    m_ManagedByTenantIdIsSet = false;
}
std::vector<utility::string_t> APITicketDetail::getAssignedUserIds() const
{
    return m_AssignedUserIds;
}


void APITicketDetail::setAssignedUserIds(const std::vector<utility::string_t>& value)
{
    m_AssignedUserIds = value;
    m_AssignedUserIdsIsSet = true;
}

bool APITicketDetail::assignedUserIdsIsSet() const
{
    return m_AssignedUserIdsIsSet;
}

void APITicketDetail::unsetAssignedUserIds()
{
    m_AssignedUserIdsIsSet = false;
}
utility::string_t APITicketDetail::getSubject() const
{
    return m_Subject;
}


void APITicketDetail::setSubject(const utility::string_t& value)
{
    m_Subject = value;
    m_SubjectIsSet = true;
}

bool APITicketDetail::subjectIsSet() const
{
    return m_SubjectIsSet;
}

void APITicketDetail::unsetSubject()
{
    m_SubjectIsSet = false;
}
utility::string_t APITicketDetail::getCreatedAt() const
{
    return m_CreatedAt;
}


void APITicketDetail::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool APITicketDetail::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void APITicketDetail::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
int32_t APITicketDetail::getState() const
{
    return m_State;
}

void APITicketDetail::setState(int32_t value)
{
    m_State = value;
    m_StateIsSet = true;
}

bool APITicketDetail::stateIsSet() const
{
    return m_StateIsSet;
}

void APITicketDetail::unsetState()
{
    m_StateIsSet = false;
}
int32_t APITicketDetail::getFileCount() const
{
    return m_FileCount;
}

void APITicketDetail::setFileCount(int32_t value)
{
    m_FileCount = value;
    m_FileCountIsSet = true;
}

bool APITicketDetail::fileCountIsSet() const
{
    return m_FileCountIsSet;
}

void APITicketDetail::unsetFileCount()
{
    m_FileCountIsSet = false;
}
std::vector<std::shared_ptr<APITicketFile>> APITicketDetail::getFiles() const
{
    return m_Files;
}


void APITicketDetail::setFiles(const std::vector<std::shared_ptr<APITicketFile>>& value)
{
    m_Files = value;
    m_FilesIsSet = true;
}

bool APITicketDetail::filesIsSet() const
{
    return m_FilesIsSet;
}

void APITicketDetail::unsetFiles()
{
    m_FilesIsSet = false;
}
utility::string_t APITicketDetail::getReopenedAt() const
{
    return m_ReopenedAt.get();
}


void APITicketDetail::setReopenedAt(const utility::string_t& value)
{
    m_ReopenedAt = value;
}

bool APITicketDetail::reopenedAtIsSet() const
{
    return m_ReopenedAt.has_value();
}

void APITicketDetail::unsetReopenedAt()
{
    m_ReopenedAt.reset();
}
utility::string_t APITicketDetail::getResolvedAt() const
{
    return m_ResolvedAt.get();
}


void APITicketDetail::setResolvedAt(const utility::string_t& value)
{
    m_ResolvedAt = value;
}

bool APITicketDetail::resolvedAtIsSet() const
{
    return m_ResolvedAt.has_value();
}

void APITicketDetail::unsetResolvedAt()
{
    m_ResolvedAt.reset();
}
utility::string_t APITicketDetail::getAckAt() const
{
    return m_AckAt.get();
}


void APITicketDetail::setAckAt(const utility::string_t& value)
{
    m_AckAt = value;
}

bool APITicketDetail::ackAtIsSet() const
{
    return m_AckAt.has_value();
}

void APITicketDetail::unsetAckAt()
{
    m_AckAt.reset();
}

}
}
}
}


