/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/BuildModerationFilterParams.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

BuildModerationFilterParams::BuildModerationFilterParams()
{
    m_UserId = utility::conversions::to_string_t("");
    m_UserIdIsSet = false;
    m_TenantId = utility::conversions::to_string_t("");
    m_TenantIdIsSet = false;
    m_Filters = utility::conversions::to_string_t("");
    m_FiltersIsSet = false;
    m_SearchFilters = utility::conversions::to_string_t("");
    m_SearchFiltersIsSet = false;
    m_TextSearch = utility::conversions::to_string_t("");
    m_TextSearchIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

BuildModerationFilterParams::~BuildModerationFilterParams()
{
}

void BuildModerationFilterParams::validate()
{
    // TODO: implement validation
}

web::json::value BuildModerationFilterParams::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UserIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("userId"))] = ModelBase::toJson(m_UserId);
    }
    if(m_TenantIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenantId"))] = ModelBase::toJson(m_TenantId);
    }
    if(m_FiltersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("filters"))] = ModelBase::toJson(m_Filters);
    }
    if(m_SearchFiltersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("searchFilters"))] = ModelBase::toJson(m_SearchFilters);
    }
    if(m_TextSearchIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("textSearch"))] = ModelBase::toJson(m_TextSearch);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool BuildModerationFilterParams::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserId);
            setUserId(refVal_setUserId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenantId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantId);
            setTenantId(refVal_setTenantId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("filters"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("filters")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFilters;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilters);
            setFilters(refVal_setFilters);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("searchFilters"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("searchFilters")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSearchFilters;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSearchFilters);
            setSearchFilters(refVal_setSearchFilters);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("textSearch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("textSearch")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTextSearch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTextSearch);
            setTextSearch(refVal_setTextSearch);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("userId"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("tenantId"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("filters"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("searchFilters"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("textSearch"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void BuildModerationFilterParams::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userId")), m_UserId));
    }
    if(m_TenantIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenantId")), m_TenantId));
    }
    if(m_FiltersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("filters")), m_Filters));
    }
    if(m_SearchFiltersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("searchFilters")), m_SearchFilters));
    }
    if(m_TextSearchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("textSearch")), m_TextSearch));
    }
}

bool BuildModerationFilterParams::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        utility::string_t refVal_setUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userId"))), refVal_setUserId );
        setUserId(refVal_setUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        utility::string_t refVal_setTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))), refVal_setTenantId );
        setTenantId(refVal_setTenantId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("filters"))))
    {
        utility::string_t refVal_setFilters;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("filters"))), refVal_setFilters );
        setFilters(refVal_setFilters);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("searchFilters"))))
    {
        utility::string_t refVal_setSearchFilters;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("searchFilters"))), refVal_setSearchFilters );
        setSearchFilters(refVal_setSearchFilters);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("textSearch"))))
    {
        utility::string_t refVal_setTextSearch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("textSearch"))), refVal_setTextSearch );
        setTextSearch(refVal_setTextSearch);
    }
    return ok;
}


utility::string_t BuildModerationFilterParams::getUserId() const
{
    return m_UserId;
}


void BuildModerationFilterParams::setUserId(const utility::string_t& value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}

bool BuildModerationFilterParams::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void BuildModerationFilterParams::unsetUserId()
{
    m_UserIdIsSet = false;
}
utility::string_t BuildModerationFilterParams::getTenantId() const
{
    return m_TenantId;
}


void BuildModerationFilterParams::setTenantId(const utility::string_t& value)
{
    m_TenantId = value;
    m_TenantIdIsSet = true;
}

bool BuildModerationFilterParams::tenantIdIsSet() const
{
    return m_TenantIdIsSet;
}

void BuildModerationFilterParams::unsetTenantId()
{
    m_TenantIdIsSet = false;
}
utility::string_t BuildModerationFilterParams::getFilters() const
{
    return m_Filters;
}


void BuildModerationFilterParams::setFilters(const utility::string_t& value)
{
    m_Filters = value;
    m_FiltersIsSet = true;
}

bool BuildModerationFilterParams::filtersIsSet() const
{
    return m_FiltersIsSet;
}

void BuildModerationFilterParams::unsetFilters()
{
    m_FiltersIsSet = false;
}
utility::string_t BuildModerationFilterParams::getSearchFilters() const
{
    return m_SearchFilters;
}


void BuildModerationFilterParams::setSearchFilters(const utility::string_t& value)
{
    m_SearchFilters = value;
    m_SearchFiltersIsSet = true;
}

bool BuildModerationFilterParams::searchFiltersIsSet() const
{
    return m_SearchFiltersIsSet;
}

void BuildModerationFilterParams::unsetSearchFilters()
{
    m_SearchFiltersIsSet = false;
}
utility::string_t BuildModerationFilterParams::getTextSearch() const
{
    return m_TextSearch;
}


void BuildModerationFilterParams::setTextSearch(const utility::string_t& value)
{
    m_TextSearch = value;
    m_TextSearchIsSet = true;
}

bool BuildModerationFilterParams::textSearchIsSet() const
{
    return m_TextSearchIsSet;
}

void BuildModerationFilterParams::unsetTextSearch()
{
    m_TextSearchIsSet = false;
}


std::map<utility::string_t, web::json::value> BuildModerationFilterParams::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void BuildModerationFilterParams::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void BuildModerationFilterParams::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool BuildModerationFilterParams::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void BuildModerationFilterParams::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}
}


