/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/BulkCreateHashTagsResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

BulkCreateHashTagsResponse::BulkCreateHashTagsResponse()
{
    m_StatusIsSet = false;
    m_ResultsIsSet = false;
}

BulkCreateHashTagsResponse::~BulkCreateHashTagsResponse()
{
}

void BulkCreateHashTagsResponse::validate()
{
    // TODO: implement validation
}

web::json::value BulkCreateHashTagsResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_ResultsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("results"))] = ModelBase::toJson(m_Results);
    }

    return val;
}

bool BulkCreateHashTagsResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("results"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("results")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AddHashTag_200_response>> refVal_setResults;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResults);
            setResults(refVal_setResults);
            
        }
    }
    return ok;
}

void BulkCreateHashTagsResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_ResultsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("results")), m_Results));
    }
}

bool BulkCreateHashTagsResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("results"))))
    {
        std::vector<std::shared_ptr<AddHashTag_200_response>> refVal_setResults;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("results"))), refVal_setResults );
        setResults(refVal_setResults);
    }
    return ok;
}


std::shared_ptr<APIStatus> BulkCreateHashTagsResponse::getStatus() const
{
    return m_Status;
}


void BulkCreateHashTagsResponse::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool BulkCreateHashTagsResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void BulkCreateHashTagsResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
std::vector<std::shared_ptr<AddHashTag_200_response>> BulkCreateHashTagsResponse::getResults() const
{
    return m_Results;
}


void BulkCreateHashTagsResponse::setResults(const std::vector<std::shared_ptr<AddHashTag_200_response>>& value)
{
    m_Results = value;
    m_ResultsIsSet = true;
}

bool BulkCreateHashTagsResponse::resultsIsSet() const
{
    return m_ResultsIsSet;
}

void BulkCreateHashTagsResponse::unsetResults()
{
    m_ResultsIsSet = false;
}

}
}
}
}


