/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/CreateTicketBody.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CreateTicketBody::CreateTicketBody()
{
    m_Subject = utility::conversions::to_string_t("");
    m_SubjectIsSet = false;
}

CreateTicketBody::~CreateTicketBody()
{
}

void CreateTicketBody::validate()
{
    // TODO: implement validation
}

web::json::value CreateTicketBody::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SubjectIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subject"))] = ModelBase::toJson(m_Subject);
    }

    return val;
}

bool CreateTicketBody::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subject")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubject);
            setSubject(refVal_setSubject);
            
        }
    }
    return ok;
}

void CreateTicketBody::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SubjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subject")), m_Subject));
    }
}

bool CreateTicketBody::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        utility::string_t refVal_setSubject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subject"))), refVal_setSubject );
        setSubject(refVal_setSubject);
    }
    return ok;
}


utility::string_t CreateTicketBody::getSubject() const
{
    return m_Subject;
}


void CreateTicketBody::setSubject(const utility::string_t& value)
{
    m_Subject = value;
    m_SubjectIsSet = true;
}

bool CreateTicketBody::subjectIsSet() const
{
    return m_SubjectIsSet;
}

void CreateTicketBody::unsetSubject()
{
    m_SubjectIsSet = false;
}

}
}
}
}


