/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/CreateSubscriptionAPIResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CreateSubscriptionAPIResponse::CreateSubscriptionAPIResponse()
{
    m_Reason = utility::conversions::to_string_t("");
    m_ReasonIsSet = false;
    m_Code = utility::conversions::to_string_t("");
    m_CodeIsSet = false;
    m_SubscriptionIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
}

CreateSubscriptionAPIResponse::~CreateSubscriptionAPIResponse()
{
}

void CreateSubscriptionAPIResponse::validate()
{
    // TODO: implement validation
}

web::json::value CreateSubscriptionAPIResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ReasonIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("reason"))] = ModelBase::toJson(m_Reason);
    }
    if(m_CodeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }
    if(m_SubscriptionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subscription"))] = ModelBase::toJson(m_Subscription);
    }
    if(m_StatusIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool CreateSubscriptionAPIResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reason")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setReason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReason);
            setReason(refVal_setReason);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subscription"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subscription")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIUserSubscription> refVal_setSubscription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubscription);
            setSubscription(refVal_setSubscription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    return ok;
}

void CreateSubscriptionAPIResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ReasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reason")), m_Reason));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
    if(m_SubscriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subscription")), m_Subscription));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
}

bool CreateSubscriptionAPIResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        utility::string_t refVal_setReason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reason"))), refVal_setReason );
        setReason(refVal_setReason);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subscription"))))
    {
        std::shared_ptr<APIUserSubscription> refVal_setSubscription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subscription"))), refVal_setSubscription );
        setSubscription(refVal_setSubscription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}


utility::string_t CreateSubscriptionAPIResponse::getReason() const
{
    return m_Reason;
}


void CreateSubscriptionAPIResponse::setReason(const utility::string_t& value)
{
    m_Reason = value;
    m_ReasonIsSet = true;
}

bool CreateSubscriptionAPIResponse::reasonIsSet() const
{
    return m_ReasonIsSet;
}

void CreateSubscriptionAPIResponse::unsetReason()
{
    m_ReasonIsSet = false;
}
utility::string_t CreateSubscriptionAPIResponse::getCode() const
{
    return m_Code;
}


void CreateSubscriptionAPIResponse::setCode(const utility::string_t& value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool CreateSubscriptionAPIResponse::codeIsSet() const
{
    return m_CodeIsSet;
}

void CreateSubscriptionAPIResponse::unsetCode()
{
    m_CodeIsSet = false;
}
std::shared_ptr<APIUserSubscription> CreateSubscriptionAPIResponse::getSubscription() const
{
    return m_Subscription;
}


void CreateSubscriptionAPIResponse::setSubscription(const std::shared_ptr<APIUserSubscription>& value)
{
    m_Subscription = value;
    m_SubscriptionIsSet = true;
}

bool CreateSubscriptionAPIResponse::subscriptionIsSet() const
{
    return m_SubscriptionIsSet;
}

void CreateSubscriptionAPIResponse::unsetSubscription()
{
    m_SubscriptionIsSet = false;
}
utility::string_t CreateSubscriptionAPIResponse::getStatus() const
{
    return m_Status;
}


void CreateSubscriptionAPIResponse::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool CreateSubscriptionAPIResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void CreateSubscriptionAPIResponse::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}
}
}


