/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/CreateTenantUserResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CreateTenantUserResponse::CreateTenantUserResponse()
{
    m_StatusIsSet = false;
    m_TenantUserIsSet = false;
}

CreateTenantUserResponse::~CreateTenantUserResponse()
{
}

void CreateTenantUserResponse::validate()
{
    // TODO: implement validation
}

web::json::value CreateTenantUserResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_TenantUserIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenantUser"))] = ModelBase::toJson(m_TenantUser);
    }

    return val;
}

bool CreateTenantUserResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenantUser"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenantUser")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<User> refVal_setTenantUser;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantUser);
            setTenantUser(refVal_setTenantUser);
            
        }
    }
    return ok;
}

void CreateTenantUserResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_TenantUserIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenantUser")), m_TenantUser));
    }
}

bool CreateTenantUserResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenantUser"))))
    {
        std::shared_ptr<User> refVal_setTenantUser;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenantUser"))), refVal_setTenantUser );
        setTenantUser(refVal_setTenantUser);
    }
    return ok;
}


std::shared_ptr<APIStatus> CreateTenantUserResponse::getStatus() const
{
    return m_Status;
}


void CreateTenantUserResponse::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool CreateTenantUserResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void CreateTenantUserResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
std::shared_ptr<User> CreateTenantUserResponse::getTenantUser() const
{
    return m_TenantUser;
}


void CreateTenantUserResponse::setTenantUser(const std::shared_ptr<User>& value)
{
    m_TenantUser = value;
    m_TenantUserIsSet = true;
}

bool CreateTenantUserResponse::tenantUserIsSet() const
{
    return m_TenantUserIsSet;
}

void CreateTenantUserResponse::unsetTenantUser()
{
    m_TenantUserIsSet = false;
}

}
}
}
}


