/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/DeleteCommentResult.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

DeleteCommentResult::DeleteCommentResult()
{
    m_ActionIsSet = false;
    m_StatusIsSet = false;
}

DeleteCommentResult::~DeleteCommentResult()
{
}

void DeleteCommentResult::validate()
{
    // TODO: implement validation
}

web::json::value DeleteCommentResult::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ActionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("action"))] = ModelBase::toJson(m_Action);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool DeleteCommentResult::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("action"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("action")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<DeleteCommentAction> refVal_setAction;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAction);
            setAction(refVal_setAction);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    return ok;
}

void DeleteCommentResult::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ActionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("action")), m_Action));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
}

bool DeleteCommentResult::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("action"))))
    {
        std::shared_ptr<DeleteCommentAction> refVal_setAction;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("action"))), refVal_setAction );
        setAction(refVal_setAction);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}


std::shared_ptr<DeleteCommentAction> DeleteCommentResult::getAction() const
{
    return m_Action;
}


void DeleteCommentResult::setAction(const std::shared_ptr<DeleteCommentAction>& value)
{
    m_Action = value;
    m_ActionIsSet = true;
}

bool DeleteCommentResult::actionIsSet() const
{
    return m_ActionIsSet;
}

void DeleteCommentResult::unsetAction()
{
    m_ActionIsSet = false;
}
std::shared_ptr<APIStatus> DeleteCommentResult::getStatus() const
{
    return m_Status;
}


void DeleteCommentResult::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool DeleteCommentResult::statusIsSet() const
{
    return m_StatusIsSet;
}

void DeleteCommentResult::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}
}
}


