/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/GetTenantUsersResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

GetTenantUsersResponse::GetTenantUsersResponse()
{
    m_StatusIsSet = false;
    m_TenantUsersIsSet = false;
}

GetTenantUsersResponse::~GetTenantUsersResponse()
{
}

void GetTenantUsersResponse::validate()
{
    // TODO: implement validation
}

web::json::value GetTenantUsersResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_TenantUsersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenantUsers"))] = ModelBase::toJson(m_TenantUsers);
    }

    return val;
}

bool GetTenantUsersResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenantUsers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenantUsers")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<User>> refVal_setTenantUsers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantUsers);
            setTenantUsers(refVal_setTenantUsers);
            
        }
    }
    return ok;
}

void GetTenantUsersResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_TenantUsersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenantUsers")), m_TenantUsers));
    }
}

bool GetTenantUsersResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenantUsers"))))
    {
        std::vector<std::shared_ptr<User>> refVal_setTenantUsers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenantUsers"))), refVal_setTenantUsers );
        setTenantUsers(refVal_setTenantUsers);
    }
    return ok;
}


std::shared_ptr<APIStatus> GetTenantUsersResponse::getStatus() const
{
    return m_Status;
}


void GetTenantUsersResponse::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool GetTenantUsersResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void GetTenantUsersResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
std::vector<std::shared_ptr<User>> GetTenantUsersResponse::getTenantUsers() const
{
    return m_TenantUsers;
}


void GetTenantUsersResponse::setTenantUsers(const std::vector<std::shared_ptr<User>>& value)
{
    m_TenantUsers = value;
    m_TenantUsersIsSet = true;
}

bool GetTenantUsersResponse::tenantUsersIsSet() const
{
    return m_TenantUsersIsSet;
}

void GetTenantUsersResponse::unsetTenantUsers()
{
    m_TenantUsersIsSet = false;
}

}
}
}
}


