/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/GetTranslationsResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

GetTranslationsResponse::GetTranslationsResponse()
{
    m_TranslationsIsSet = false;
    m_StatusIsSet = false;
}

GetTranslationsResponse::~GetTranslationsResponse()
{
}

void GetTranslationsResponse::validate()
{
    // TODO: implement validation
}

web::json::value GetTranslationsResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TranslationsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("translations"))] = ModelBase::toJson(m_Translations);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool GetTranslationsResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("translations"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("translations")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setTranslations;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTranslations);
            setTranslations(refVal_setTranslations);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    return ok;
}

void GetTranslationsResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TranslationsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("translations")), m_Translations));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
}

bool GetTranslationsResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("translations"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setTranslations;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("translations"))), refVal_setTranslations );
        setTranslations(refVal_setTranslations);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}


std::map<utility::string_t, utility::string_t> GetTranslationsResponse::getTranslations() const
{
    return m_Translations;
}


void GetTranslationsResponse::setTranslations(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Translations = value;
    m_TranslationsIsSet = true;
}

bool GetTranslationsResponse::translationsIsSet() const
{
    return m_TranslationsIsSet;
}

void GetTranslationsResponse::unsetTranslations()
{
    m_TranslationsIsSet = false;
}
std::shared_ptr<APIStatus> GetTranslationsResponse::getStatus() const
{
    return m_Status;
}


void GetTranslationsResponse::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool GetTranslationsResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void GetTranslationsResponse::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}
}
}


