/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/ModerationAPICommentLog.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ModerationAPICommentLog::ModerationAPICommentLog()
{
    m_date = utility::datetime();
    m_dateIsSet = false;
    m_Username = utility::conversions::to_string_t("");
    m_UsernameIsSet = false;
    m_ActionName = utility::conversions::to_string_t("");
    m_ActionNameIsSet = false;
    m_MessageHTML = utility::conversions::to_string_t("");
    m_MessageHTMLIsSet = false;
}

ModerationAPICommentLog::~ModerationAPICommentLog()
{
}

void ModerationAPICommentLog::validate()
{
    // TODO: implement validation
}

web::json::value ModerationAPICommentLog::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_dateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("date"))] = ModelBase::toJson(m_date);
    }
    if(m_UsernameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("username"))] = ModelBase::toJson(m_Username);
    }
    if(m_ActionNameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("actionName"))] = ModelBase::toJson(m_ActionName);
    }
    if(m_MessageHTMLIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("messageHTML"))] = ModelBase::toJson(m_MessageHTML);
    }

    return val;
}

bool ModerationAPICommentLog::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("date"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("date")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDate);
            setDate(refVal_setDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("username"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("username")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUsername;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUsername);
            setUsername(refVal_setUsername);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("actionName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("actionName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setActionName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActionName);
            setActionName(refVal_setActionName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("messageHTML"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("messageHTML")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMessageHTML;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessageHTML);
            setMessageHTML(refVal_setMessageHTML);
            
        }
    }
    return ok;
}

void ModerationAPICommentLog::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_dateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("date")), m_date));
    }
    if(m_UsernameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("username")), m_Username));
    }
    if(m_ActionNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("actionName")), m_ActionName));
    }
    if(m_MessageHTMLIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("messageHTML")), m_MessageHTML));
    }
}

bool ModerationAPICommentLog::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("date"))))
    {
        utility::datetime refVal_setDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("date"))), refVal_setDate );
        setDate(refVal_setDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("username"))))
    {
        utility::string_t refVal_setUsername;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("username"))), refVal_setUsername );
        setUsername(refVal_setUsername);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("actionName"))))
    {
        utility::string_t refVal_setActionName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("actionName"))), refVal_setActionName );
        setActionName(refVal_setActionName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("messageHTML"))))
    {
        utility::string_t refVal_setMessageHTML;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("messageHTML"))), refVal_setMessageHTML );
        setMessageHTML(refVal_setMessageHTML);
    }
    return ok;
}


utility::datetime ModerationAPICommentLog::getDate() const
{
    return m_date;
}


void ModerationAPICommentLog::setDate(const utility::datetime& value)
{
    m_date = value;
    m_dateIsSet = true;
}

bool ModerationAPICommentLog::dateIsSet() const
{
    return m_dateIsSet;
}

void ModerationAPICommentLog::unsetdate()
{
    m_dateIsSet = false;
}
utility::string_t ModerationAPICommentLog::getUsername() const
{
    return m_Username;
}


void ModerationAPICommentLog::setUsername(const utility::string_t& value)
{
    m_Username = value;
    m_UsernameIsSet = true;
}

bool ModerationAPICommentLog::usernameIsSet() const
{
    return m_UsernameIsSet;
}

void ModerationAPICommentLog::unsetUsername()
{
    m_UsernameIsSet = false;
}
utility::string_t ModerationAPICommentLog::getActionName() const
{
    return m_ActionName;
}


void ModerationAPICommentLog::setActionName(const utility::string_t& value)
{
    m_ActionName = value;
    m_ActionNameIsSet = true;
}

bool ModerationAPICommentLog::actionNameIsSet() const
{
    return m_ActionNameIsSet;
}

void ModerationAPICommentLog::unsetActionName()
{
    m_ActionNameIsSet = false;
}
utility::string_t ModerationAPICommentLog::getMessageHTML() const
{
    return m_MessageHTML;
}


void ModerationAPICommentLog::setMessageHTML(const utility::string_t& value)
{
    m_MessageHTML = value;
    m_MessageHTMLIsSet = true;
}

bool ModerationAPICommentLog::messageHTMLIsSet() const
{
    return m_MessageHTMLIsSet;
}

void ModerationAPICommentLog::unsetMessageHTML()
{
    m_MessageHTMLIsSet = false;
}

}
}
}
}


