/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/NotificationObjectType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = int64_t;

NotificationObjectType::eNotificationObjectType toEnum(const EnumUnderlyingType& val)
{
    switch (val)
    {
    case 0:
        return NotificationObjectType::eNotificationObjectType::_0;
    case 1:
        return NotificationObjectType::eNotificationObjectType::_1;
    case 2:
        return NotificationObjectType::eNotificationObjectType::_2;
    default:
        break;
    }
    return {};
}

EnumUnderlyingType fromEnum(NotificationObjectType::eNotificationObjectType e)
{
    switch (e)
    {
    case NotificationObjectType::eNotificationObjectType::_0:
        return 0;
    case NotificationObjectType::eNotificationObjectType::_1:
        return 1;
    case NotificationObjectType::eNotificationObjectType::_2:
        return 2;
    default:
        break;
    }
    return {};
}
}

NotificationObjectType::NotificationObjectType()
{
}

NotificationObjectType::~NotificationObjectType()
{
}

void NotificationObjectType::validate()
{
    // TODO: implement validation
}

web::json::value NotificationObjectType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool NotificationObjectType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_number().to_int64());
    return true;
}

void NotificationObjectType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool NotificationObjectType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

NotificationObjectType::eNotificationObjectType NotificationObjectType::getValue() const
{
   return m_value;
}

void NotificationObjectType::setValue(NotificationObjectType::eNotificationObjectType const value)
{
   m_value = value;
}

NotificationObjectType::NotificationObjectType(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


