/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/PublicAPISetCommentTextResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PublicAPISetCommentTextResponse::PublicAPISetCommentTextResponse()
{
    m_CommentIsSet = false;
    m_StatusIsSet = false;
}

PublicAPISetCommentTextResponse::~PublicAPISetCommentTextResponse()
{
}

void PublicAPISetCommentTextResponse::validate()
{
    // TODO: implement validation
}

web::json::value PublicAPISetCommentTextResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CommentIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("comment"))] = ModelBase::toJson(m_Comment);
    }
    if(m_StatusIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool PublicAPISetCommentTextResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("comment"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("comment")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Pick_FComment_approved_or_commentHTML_> refVal_setComment;
            ok &= ModelBase::fromJson(fieldValue, refVal_setComment);
            setComment(refVal_setComment);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ImportedAPIStatus_SUCCESS> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    return ok;
}

void PublicAPISetCommentTextResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CommentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("comment")), m_Comment));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
}

bool PublicAPISetCommentTextResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("comment"))))
    {
        std::shared_ptr<Pick_FComment_approved_or_commentHTML_> refVal_setComment;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("comment"))), refVal_setComment );
        setComment(refVal_setComment);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<ImportedAPIStatus_SUCCESS> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}


std::shared_ptr<Pick_FComment_approved_or_commentHTML_> PublicAPISetCommentTextResponse::getComment() const
{
    return m_Comment;
}


void PublicAPISetCommentTextResponse::setComment(const std::shared_ptr<Pick_FComment_approved_or_commentHTML_>& value)
{
    m_Comment = value;
    m_CommentIsSet = true;
}

bool PublicAPISetCommentTextResponse::commentIsSet() const
{
    return m_CommentIsSet;
}

void PublicAPISetCommentTextResponse::unsetComment()
{
    m_CommentIsSet = false;
}
std::shared_ptr<ImportedAPIStatus_SUCCESS> PublicAPISetCommentTextResponse::getStatus() const
{
    return m_Status;
}


void PublicAPISetCommentTextResponse::setStatus(const std::shared_ptr<ImportedAPIStatus_SUCCESS>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool PublicAPISetCommentTextResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void PublicAPISetCommentTextResponse::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}
}
}


