/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/QuestionResult.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

QuestionResult::QuestionResult()
{
    m__id = utility::conversions::to_string_t("");
    m__idIsSet = false;
    m_TenantId = utility::conversions::to_string_t("");
    m_TenantIdIsSet = false;
    m_UrlId = utility::conversions::to_string_t("");
    m_UrlIdIsSet = false;
    m_AnonUserId = utility::conversions::to_string_t("");
    m_AnonUserIdIsSet = false;
    m_UserId = utility::conversions::to_string_t("");
    m_UserIdIsSet = false;
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
    m_Value = 0;
    m_ValueIsSet = false;
    m_CommentId = utility::conversions::to_string_t("");
    m_CommentIdIsSet = false;
    m_QuestionId = utility::conversions::to_string_t("");
    m_QuestionIdIsSet = false;
    m_MetaIsSet = false;
    m_IpHash = utility::conversions::to_string_t("");
    m_IpHashIsSet = false;
}

QuestionResult::~QuestionResult()
{
}

void QuestionResult::validate()
{
    // TODO: implement validation
}

web::json::value QuestionResult::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m__idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("_id"))] = ModelBase::toJson(m__id);
    }
    if(m_TenantIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenantId"))] = ModelBase::toJson(m_TenantId);
    }
    if(m_UrlIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("urlId"))] = ModelBase::toJson(m_UrlId);
    }
    if(m_AnonUserIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("anonUserId"))] = ModelBase::toJson(m_AnonUserId);
    }
    if(m_UserIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("userId"))] = ModelBase::toJson(m_UserId);
    }
    if(m_CreatedAtIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_ValueIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("value"))] = ModelBase::toJson(m_Value);
    }
    if(m_CommentIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("commentId"))] = ModelBase::toJson(m_CommentId);
    }
    if(m_QuestionIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("questionId"))] = ModelBase::toJson(m_QuestionId);
    }
    if(m_MetaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("meta"))] = ModelBase::toJson(m_Meta);
    }
    if(m_IpHashIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("ipHash"))] = ModelBase::toJson(m_IpHash);
    }

    return val;
}

bool QuestionResult::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenantId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantId);
            setTenantId(refVal_setTenantId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("urlId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("urlId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrlId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrlId);
            setUrlId(refVal_setUrlId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("anonUserId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("anonUserId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAnonUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAnonUserId);
            setAnonUserId(refVal_setAnonUserId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserId);
            setUserId(refVal_setUserId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("value")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("commentId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("commentId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCommentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCommentId);
            setCommentId(refVal_setCommentId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("questionId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("questionId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuestionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuestionId);
            setQuestionId(refVal_setQuestionId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("meta"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("meta")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<MetaItem>> refVal_setMeta;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMeta);
            setMeta(refVal_setMeta);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ipHash"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ipHash")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIpHash;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIpHash);
            setIpHash(refVal_setIpHash);
            
        }
    }
    return ok;
}

void QuestionResult::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m__idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("_id")), m__id));
    }
    if(m_TenantIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenantId")), m_TenantId));
    }
    if(m_UrlIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("urlId")), m_UrlId));
    }
    if(m_AnonUserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("anonUserId")), m_AnonUserId));
    }
    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userId")), m_UserId));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("value")), m_Value));
    }
    if(m_CommentIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("commentId")), m_CommentId));
    }
    if(m_QuestionIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("questionId")), m_QuestionId));
    }
    if(m_MetaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("meta")), m_Meta));
    }
    if(m_IpHashIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ipHash")), m_IpHash));
    }
}

bool QuestionResult::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("_id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        utility::string_t refVal_setTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))), refVal_setTenantId );
        setTenantId(refVal_setTenantId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("urlId"))))
    {
        utility::string_t refVal_setUrlId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("urlId"))), refVal_setUrlId );
        setUrlId(refVal_setUrlId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("anonUserId"))))
    {
        utility::string_t refVal_setAnonUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("anonUserId"))), refVal_setAnonUserId );
        setAnonUserId(refVal_setAnonUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        utility::string_t refVal_setUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userId"))), refVal_setUserId );
        setUserId(refVal_setUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        int32_t refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("commentId"))))
    {
        utility::string_t refVal_setCommentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("commentId"))), refVal_setCommentId );
        setCommentId(refVal_setCommentId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("questionId"))))
    {
        utility::string_t refVal_setQuestionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("questionId"))), refVal_setQuestionId );
        setQuestionId(refVal_setQuestionId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("meta"))))
    {
        std::vector<std::shared_ptr<MetaItem>> refVal_setMeta;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("meta"))), refVal_setMeta );
        setMeta(refVal_setMeta);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ipHash"))))
    {
        utility::string_t refVal_setIpHash;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ipHash"))), refVal_setIpHash );
        setIpHash(refVal_setIpHash);
    }
    return ok;
}


utility::string_t QuestionResult::getId() const
{
    return m__id;
}


void QuestionResult::setId(const utility::string_t& value)
{
    m__id = value;
    m__idIsSet = true;
}

bool QuestionResult::idIsSet() const
{
    return m__idIsSet;
}

void QuestionResult::unset_id()
{
    m__idIsSet = false;
}
utility::string_t QuestionResult::getTenantId() const
{
    return m_TenantId;
}


void QuestionResult::setTenantId(const utility::string_t& value)
{
    m_TenantId = value;
    m_TenantIdIsSet = true;
}

bool QuestionResult::tenantIdIsSet() const
{
    return m_TenantIdIsSet;
}

void QuestionResult::unsetTenantId()
{
    m_TenantIdIsSet = false;
}
utility::string_t QuestionResult::getUrlId() const
{
    return m_UrlId;
}


void QuestionResult::setUrlId(const utility::string_t& value)
{
    m_UrlId = value;
    m_UrlIdIsSet = true;
}

bool QuestionResult::urlIdIsSet() const
{
    return m_UrlIdIsSet;
}

void QuestionResult::unsetUrlId()
{
    m_UrlIdIsSet = false;
}
utility::string_t QuestionResult::getAnonUserId() const
{
    return m_AnonUserId;
}


void QuestionResult::setAnonUserId(const utility::string_t& value)
{
    m_AnonUserId = value;
    m_AnonUserIdIsSet = true;
}

bool QuestionResult::anonUserIdIsSet() const
{
    return m_AnonUserIdIsSet;
}

void QuestionResult::unsetAnonUserId()
{
    m_AnonUserIdIsSet = false;
}
utility::string_t QuestionResult::getUserId() const
{
    return m_UserId;
}


void QuestionResult::setUserId(const utility::string_t& value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}

bool QuestionResult::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void QuestionResult::unsetUserId()
{
    m_UserIdIsSet = false;
}
utility::datetime QuestionResult::getCreatedAt() const
{
    return m_CreatedAt;
}


void QuestionResult::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool QuestionResult::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void QuestionResult::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
int32_t QuestionResult::getValue() const
{
    return m_Value;
}

void QuestionResult::setValue(int32_t value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool QuestionResult::valueIsSet() const
{
    return m_ValueIsSet;
}

void QuestionResult::unsetValue()
{
    m_ValueIsSet = false;
}
utility::string_t QuestionResult::getCommentId() const
{
    return m_CommentId;
}


void QuestionResult::setCommentId(const utility::string_t& value)
{
    m_CommentId = value;
    m_CommentIdIsSet = true;
}

bool QuestionResult::commentIdIsSet() const
{
    return m_CommentIdIsSet;
}

void QuestionResult::unsetCommentId()
{
    m_CommentIdIsSet = false;
}
utility::string_t QuestionResult::getQuestionId() const
{
    return m_QuestionId;
}


void QuestionResult::setQuestionId(const utility::string_t& value)
{
    m_QuestionId = value;
    m_QuestionIdIsSet = true;
}

bool QuestionResult::questionIdIsSet() const
{
    return m_QuestionIdIsSet;
}

void QuestionResult::unsetQuestionId()
{
    m_QuestionIdIsSet = false;
}
std::vector<std::shared_ptr<MetaItem>> QuestionResult::getMeta() const
{
    return m_Meta;
}


void QuestionResult::setMeta(const std::vector<std::shared_ptr<MetaItem>>& value)
{
    m_Meta = value;
    m_MetaIsSet = true;
}

bool QuestionResult::metaIsSet() const
{
    return m_MetaIsSet;
}

void QuestionResult::unsetMeta()
{
    m_MetaIsSet = false;
}
utility::string_t QuestionResult::getIpHash() const
{
    return m_IpHash;
}


void QuestionResult::setIpHash(const utility::string_t& value)
{
    m_IpHash = value;
    m_IpHashIsSet = true;
}

bool QuestionResult::ipHashIsSet() const
{
    return m_IpHashIsSet;
}

void QuestionResult::unsetIpHash()
{
    m_IpHashIsSet = false;
}

}
}
}
}


