/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/RenderEmailTemplateResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RenderEmailTemplateResponse::RenderEmailTemplateResponse()
{
    m_StatusIsSet = false;
    m_Html = utility::conversions::to_string_t("");
    m_HtmlIsSet = false;
}

RenderEmailTemplateResponse::~RenderEmailTemplateResponse()
{
}

void RenderEmailTemplateResponse::validate()
{
    // TODO: implement validation
}

web::json::value RenderEmailTemplateResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_HtmlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("html"))] = ModelBase::toJson(m_Html);
    }

    return val;
}

bool RenderEmailTemplateResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("html"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("html")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHtml;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHtml);
            setHtml(refVal_setHtml);
            
        }
    }
    return ok;
}

void RenderEmailTemplateResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_HtmlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("html")), m_Html));
    }
}

bool RenderEmailTemplateResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("html"))))
    {
        utility::string_t refVal_setHtml;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("html"))), refVal_setHtml );
        setHtml(refVal_setHtml);
    }
    return ok;
}


std::shared_ptr<APIStatus> RenderEmailTemplateResponse::getStatus() const
{
    return m_Status;
}


void RenderEmailTemplateResponse::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool RenderEmailTemplateResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void RenderEmailTemplateResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t RenderEmailTemplateResponse::getHtml() const
{
    return m_Html;
}


void RenderEmailTemplateResponse::setHtml(const utility::string_t& value)
{
    m_Html = value;
    m_HtmlIsSet = true;
}

bool RenderEmailTemplateResponse::htmlIsSet() const
{
    return m_HtmlIsSet;
}

void RenderEmailTemplateResponse::unsetHtml()
{
    m_HtmlIsSet = false;
}

}
}
}
}


