/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/RenderEmailTemplateBody.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RenderEmailTemplateBody::RenderEmailTemplateBody()
{
    m_EmailTemplateId = utility::conversions::to_string_t("");
    m_EmailTemplateIdIsSet = false;
    m_Ejs = utility::conversions::to_string_t("");
    m_EjsIsSet = false;
    m_TestDataIsSet = false;
    m_TranslationOverridesByLocaleIsSet = false;
}

RenderEmailTemplateBody::~RenderEmailTemplateBody()
{
}

void RenderEmailTemplateBody::validate()
{
    // TODO: implement validation
}

web::json::value RenderEmailTemplateBody::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_EmailTemplateIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("emailTemplateId"))] = ModelBase::toJson(m_EmailTemplateId);
    }
    if(m_EjsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("ejs"))] = ModelBase::toJson(m_Ejs);
    }
    if(m_TestDataIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("testData"))] = ModelBase::toJson(m_TestData);
    }
    if(m_TranslationOverridesByLocaleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("translationOverridesByLocale"))] = ModelBase::toJson(m_TranslationOverridesByLocale);
    }

    return val;
}

bool RenderEmailTemplateBody::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("emailTemplateId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("emailTemplateId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmailTemplateId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmailTemplateId);
            setEmailTemplateId(refVal_setEmailTemplateId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ejs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ejs")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEjs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEjs);
            setEjs(refVal_setEjs);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("testData"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("testData")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setTestData;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTestData);
            setTestData(refVal_setTestData);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("translationOverridesByLocale"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("translationOverridesByLocale")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::map<utility::string_t, utility::string_t>> refVal_setTranslationOverridesByLocale;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTranslationOverridesByLocale);
            setTranslationOverridesByLocale(refVal_setTranslationOverridesByLocale);
            
        }
    }
    return ok;
}

void RenderEmailTemplateBody::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_EmailTemplateIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("emailTemplateId")), m_EmailTemplateId));
    }
    if(m_EjsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ejs")), m_Ejs));
    }
    if(m_TestDataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("testData")), m_TestData));
    }
    if(m_TranslationOverridesByLocaleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("translationOverridesByLocale")), m_TranslationOverridesByLocale));
    }
}

bool RenderEmailTemplateBody::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("emailTemplateId"))))
    {
        utility::string_t refVal_setEmailTemplateId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("emailTemplateId"))), refVal_setEmailTemplateId );
        setEmailTemplateId(refVal_setEmailTemplateId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ejs"))))
    {
        utility::string_t refVal_setEjs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ejs"))), refVal_setEjs );
        setEjs(refVal_setEjs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("testData"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setTestData;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("testData"))), refVal_setTestData );
        setTestData(refVal_setTestData);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("translationOverridesByLocale"))))
    {
        std::map<utility::string_t, std::map<utility::string_t, utility::string_t>> refVal_setTranslationOverridesByLocale;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("translationOverridesByLocale"))), refVal_setTranslationOverridesByLocale );
        setTranslationOverridesByLocale(refVal_setTranslationOverridesByLocale);
    }
    return ok;
}


utility::string_t RenderEmailTemplateBody::getEmailTemplateId() const
{
    return m_EmailTemplateId;
}


void RenderEmailTemplateBody::setEmailTemplateId(const utility::string_t& value)
{
    m_EmailTemplateId = value;
    m_EmailTemplateIdIsSet = true;
}

bool RenderEmailTemplateBody::emailTemplateIdIsSet() const
{
    return m_EmailTemplateIdIsSet;
}

void RenderEmailTemplateBody::unsetEmailTemplateId()
{
    m_EmailTemplateIdIsSet = false;
}
utility::string_t RenderEmailTemplateBody::getEjs() const
{
    return m_Ejs;
}


void RenderEmailTemplateBody::setEjs(const utility::string_t& value)
{
    m_Ejs = value;
    m_EjsIsSet = true;
}

bool RenderEmailTemplateBody::ejsIsSet() const
{
    return m_EjsIsSet;
}

void RenderEmailTemplateBody::unsetEjs()
{
    m_EjsIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> RenderEmailTemplateBody::getTestData() const
{
    return m_TestData;
}


void RenderEmailTemplateBody::setTestData(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_TestData = value;
    m_TestDataIsSet = true;
}

bool RenderEmailTemplateBody::testDataIsSet() const
{
    return m_TestDataIsSet;
}

void RenderEmailTemplateBody::unsetTestData()
{
    m_TestDataIsSet = false;
}
std::map<utility::string_t, std::map<utility::string_t, utility::string_t>> RenderEmailTemplateBody::getTranslationOverridesByLocale() const
{
    return m_TranslationOverridesByLocale;
}


void RenderEmailTemplateBody::setTranslationOverridesByLocale(const std::map<utility::string_t, std::map<utility::string_t, utility::string_t>>& value)
{
    m_TranslationOverridesByLocale = value;
    m_TranslationOverridesByLocaleIsSet = true;
}

bool RenderEmailTemplateBody::translationOverridesByLocaleIsSet() const
{
    return m_TranslationOverridesByLocaleIsSet;
}

void RenderEmailTemplateBody::unsetTranslationOverridesByLocale()
{
    m_TranslationOverridesByLocaleIsSet = false;
}

}
}
}
}


