/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/TenantHashTag.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

TenantHashTag::TenantHashTag()
{
    m__id = utility::conversions::to_string_t("");
    m__idIsSet = false;
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
    m_TenantId = utility::conversions::to_string_t("");
    m_TenantIdIsSet = false;
    m_Tag = utility::conversions::to_string_t("");
    m_TagIsSet = false;
    m_Url = utility::conversions::to_string_t("");
    m_UrlIsSet = false;
}

TenantHashTag::~TenantHashTag()
{
}

void TenantHashTag::validate()
{
    // TODO: implement validation
}

web::json::value TenantHashTag::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m__idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("_id"))] = ModelBase::toJson(m__id);
    }
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_TenantIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenantId"))] = ModelBase::toJson(m_TenantId);
    }
    if(m_TagIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tag"))] = ModelBase::toJson(m_Tag);
    }
    if(m_UrlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("url"))] = ModelBase::toJson(m_Url);
    }

    return val;
}

bool TenantHashTag::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenantId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantId);
            setTenantId(refVal_setTenantId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tag"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tag")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTag;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTag);
            setTag(refVal_setTag);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrl);
            setUrl(refVal_setUrl);
            
        }
    }
    return ok;
}

void TenantHashTag::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m__idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("_id")), m__id));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_TenantIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenantId")), m_TenantId));
    }
    if(m_TagIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tag")), m_Tag));
    }
    if(m_UrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("url")), m_Url));
    }
}

bool TenantHashTag::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("_id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        utility::string_t refVal_setTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))), refVal_setTenantId );
        setTenantId(refVal_setTenantId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tag"))))
    {
        utility::string_t refVal_setTag;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tag"))), refVal_setTag );
        setTag(refVal_setTag);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("url"))))
    {
        utility::string_t refVal_setUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("url"))), refVal_setUrl );
        setUrl(refVal_setUrl);
    }
    return ok;
}


utility::string_t TenantHashTag::getId() const
{
    return m__id;
}


void TenantHashTag::setId(const utility::string_t& value)
{
    m__id = value;
    m__idIsSet = true;
}

bool TenantHashTag::idIsSet() const
{
    return m__idIsSet;
}

void TenantHashTag::unset_id()
{
    m__idIsSet = false;
}
utility::datetime TenantHashTag::getCreatedAt() const
{
    return m_CreatedAt;
}


void TenantHashTag::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool TenantHashTag::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void TenantHashTag::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
utility::string_t TenantHashTag::getTenantId() const
{
    return m_TenantId;
}


void TenantHashTag::setTenantId(const utility::string_t& value)
{
    m_TenantId = value;
    m_TenantIdIsSet = true;
}

bool TenantHashTag::tenantIdIsSet() const
{
    return m_TenantIdIsSet;
}

void TenantHashTag::unsetTenantId()
{
    m_TenantIdIsSet = false;
}
utility::string_t TenantHashTag::getTag() const
{
    return m_Tag;
}


void TenantHashTag::setTag(const utility::string_t& value)
{
    m_Tag = value;
    m_TagIsSet = true;
}

bool TenantHashTag::tagIsSet() const
{
    return m_TagIsSet;
}

void TenantHashTag::unsetTag()
{
    m_TagIsSet = false;
}
utility::string_t TenantHashTag::getUrl() const
{
    return m_Url;
}


void TenantHashTag::setUrl(const utility::string_t& value)
{
    m_Url = value;
    m_UrlIsSet = true;
}

bool TenantHashTag::urlIsSet() const
{
    return m_UrlIsSet;
}

void TenantHashTag::unsetUrl()
{
    m_UrlIsSet = false;
}

}
}
}
}


