/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/UpdateUserNotificationStatus_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UpdateUserNotificationStatus_200_response::UpdateUserNotificationStatus_200_response()
{
    m_StatusIsSet = false;
    m_MatchedCount = 0L;
    m_MatchedCountIsSet = false;
    m_ModifiedCount = 0L;
    m_ModifiedCountIsSet = false;
    m_NoteIsSet = false;
    m_Reason = utility::conversions::to_string_t("");
    m_ReasonIsSet = false;
    m_Code = utility::conversions::to_string_t("");
    m_CodeIsSet = false;
    m_SecondaryCode = utility::conversions::to_string_t("");
    m_SecondaryCodeIsSet = false;
    m_BannedUntil = 0L;
    m_BannedUntilIsSet = false;
    m_MaxCharacterLength = 0;
    m_MaxCharacterLengthIsSet = false;
    m_TranslatedError = utility::conversions::to_string_t("");
    m_TranslatedErrorIsSet = false;
    m_CustomConfigIsSet = false;
}

UpdateUserNotificationStatus_200_response::~UpdateUserNotificationStatus_200_response()
{
}

void UpdateUserNotificationStatus_200_response::validate()
{
    // TODO: implement validation
}

web::json::value UpdateUserNotificationStatus_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_MatchedCountIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("matchedCount"))] = ModelBase::toJson(m_MatchedCount);
    }
    if(m_ModifiedCountIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("modifiedCount"))] = ModelBase::toJson(m_ModifiedCount);
    }
    if(m_NoteIsSet)
    {   
        
        utility::string_t refVal = fromNoteEnum(m_Note);
        val[utility::conversions::to_string_t(_XPLATSTR("note"))] = ModelBase::toJson(refVal);
        
    }
    if(m_ReasonIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("reason"))] = ModelBase::toJson(m_Reason);
    }
    if(m_CodeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }
    if(m_SecondaryCodeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("secondaryCode"))] = ModelBase::toJson(m_SecondaryCode);
    }
    if(m_BannedUntilIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("bannedUntil"))] = ModelBase::toJson(m_BannedUntil);
    }
    if(m_MaxCharacterLengthIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("maxCharacterLength"))] = ModelBase::toJson(m_MaxCharacterLength);
    }
    if(m_TranslatedErrorIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("translatedError"))] = ModelBase::toJson(m_TranslatedError);
    }
    if(m_CustomConfigIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("customConfig"))] = ModelBase::toJson(m_CustomConfig);
    }

    return val;
}

bool UpdateUserNotificationStatus_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<APIStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("matchedCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("matchedCount")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setMatchedCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMatchedCount);
            setMatchedCount(refVal_setMatchedCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("modifiedCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("modifiedCount")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setModifiedCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModifiedCount);
            setModifiedCount(refVal_setModifiedCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("note"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("note")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNote;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNote);
            
            setNote(toNoteEnum(refVal_setNote));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reason")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setReason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReason);
            setReason(refVal_setReason);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("secondaryCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("secondaryCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSecondaryCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSecondaryCode);
            setSecondaryCode(refVal_setSecondaryCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("bannedUntil"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("bannedUntil")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setBannedUntil;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBannedUntil);
            setBannedUntil(refVal_setBannedUntil);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("maxCharacterLength"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("maxCharacterLength")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMaxCharacterLength;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxCharacterLength);
            setMaxCharacterLength(refVal_setMaxCharacterLength);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("translatedError"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("translatedError")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTranslatedError;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTranslatedError);
            setTranslatedError(refVal_setTranslatedError);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customConfig"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customConfig")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<CustomConfigParameters> refVal_setCustomConfig;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomConfig);
            setCustomConfig(refVal_setCustomConfig);
            
        }
    }
    return ok;
}

void UpdateUserNotificationStatus_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_MatchedCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("matchedCount")), m_MatchedCount));
    }
    if(m_ModifiedCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("modifiedCount")), m_ModifiedCount));
    }
    if(m_NoteIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("note")), fromNoteEnum(m_Note)));
    }
    if(m_ReasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reason")), m_Reason));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
    if(m_SecondaryCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("secondaryCode")), m_SecondaryCode));
    }
    if(m_BannedUntilIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("bannedUntil")), m_BannedUntil));
    }
    if(m_MaxCharacterLengthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("maxCharacterLength")), m_MaxCharacterLength));
    }
    if(m_TranslatedErrorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("translatedError")), m_TranslatedError));
    }
    if(m_CustomConfigIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customConfig")), m_CustomConfig));
    }
}

bool UpdateUserNotificationStatus_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<APIStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("matchedCount"))))
    {
        int64_t refVal_setMatchedCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("matchedCount"))), refVal_setMatchedCount );
        setMatchedCount(refVal_setMatchedCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("modifiedCount"))))
    {
        int64_t refVal_setModifiedCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("modifiedCount"))), refVal_setModifiedCount );
        setModifiedCount(refVal_setModifiedCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("note"))))
    {
        utility::string_t refVal_setNote;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("note"))), refVal_setNote );
        setNote(toNoteEnum(refVal_setNote));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        utility::string_t refVal_setReason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reason"))), refVal_setReason );
        setReason(refVal_setReason);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("secondaryCode"))))
    {
        utility::string_t refVal_setSecondaryCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("secondaryCode"))), refVal_setSecondaryCode );
        setSecondaryCode(refVal_setSecondaryCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("bannedUntil"))))
    {
        int64_t refVal_setBannedUntil;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("bannedUntil"))), refVal_setBannedUntil );
        setBannedUntil(refVal_setBannedUntil);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("maxCharacterLength"))))
    {
        int32_t refVal_setMaxCharacterLength;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("maxCharacterLength"))), refVal_setMaxCharacterLength );
        setMaxCharacterLength(refVal_setMaxCharacterLength);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("translatedError"))))
    {
        utility::string_t refVal_setTranslatedError;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("translatedError"))), refVal_setTranslatedError );
        setTranslatedError(refVal_setTranslatedError);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customConfig"))))
    {
        std::shared_ptr<CustomConfigParameters> refVal_setCustomConfig;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customConfig"))), refVal_setCustomConfig );
        setCustomConfig(refVal_setCustomConfig);
    }
    return ok;
}

UpdateUserNotificationStatus_200_response::NoteEnum UpdateUserNotificationStatus_200_response::toNoteEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("ignored-since-impersonated")) {
        return NoteEnum::IGNORED_SINCE_IMPERSONATED;
    }
    
    if (value == utility::conversions::to_string_t("demo-noop")) {
        return NoteEnum::DEMO_NOOP;
    }
    
    throw std::invalid_argument("Invalid value for conversion to NoteEnum");
}


const utility::string_t UpdateUserNotificationStatus_200_response::fromNoteEnum(const NoteEnum value) const
{
    switch(value)
    {
        
        case NoteEnum::IGNORED_SINCE_IMPERSONATED: return utility::conversions::to_string_t("ignored-since-impersonated");
        
        case NoteEnum::DEMO_NOOP: return utility::conversions::to_string_t("demo-noop");
        
    }
}


std::shared_ptr<APIStatus> UpdateUserNotificationStatus_200_response::getStatus() const
{
    return m_Status;
}


void UpdateUserNotificationStatus_200_response::setStatus(const std::shared_ptr<APIStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::statusIsSet() const
{
    return m_StatusIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetStatus()
{
    m_StatusIsSet = false;
}
int64_t UpdateUserNotificationStatus_200_response::getMatchedCount() const
{
    return m_MatchedCount;
}

void UpdateUserNotificationStatus_200_response::setMatchedCount(int64_t value)
{
    m_MatchedCount = value;
    m_MatchedCountIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::matchedCountIsSet() const
{
    return m_MatchedCountIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetMatchedCount()
{
    m_MatchedCountIsSet = false;
}
int64_t UpdateUserNotificationStatus_200_response::getModifiedCount() const
{
    return m_ModifiedCount;
}

void UpdateUserNotificationStatus_200_response::setModifiedCount(int64_t value)
{
    m_ModifiedCount = value;
    m_ModifiedCountIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::modifiedCountIsSet() const
{
    return m_ModifiedCountIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetModifiedCount()
{
    m_ModifiedCountIsSet = false;
}
UpdateUserNotificationStatus_200_response::NoteEnum UpdateUserNotificationStatus_200_response::getNote() const
{
    return m_Note;
}


void UpdateUserNotificationStatus_200_response::setNote(const NoteEnum value)
{
    m_Note = value;
    m_NoteIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::noteIsSet() const
{
    return m_NoteIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetNote()
{
    m_NoteIsSet = false;
}
utility::string_t UpdateUserNotificationStatus_200_response::getReason() const
{
    return m_Reason;
}


void UpdateUserNotificationStatus_200_response::setReason(const utility::string_t& value)
{
    m_Reason = value;
    m_ReasonIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::reasonIsSet() const
{
    return m_ReasonIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetReason()
{
    m_ReasonIsSet = false;
}
utility::string_t UpdateUserNotificationStatus_200_response::getCode() const
{
    return m_Code;
}


void UpdateUserNotificationStatus_200_response::setCode(const utility::string_t& value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::codeIsSet() const
{
    return m_CodeIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetCode()
{
    m_CodeIsSet = false;
}
utility::string_t UpdateUserNotificationStatus_200_response::getSecondaryCode() const
{
    return m_SecondaryCode;
}


void UpdateUserNotificationStatus_200_response::setSecondaryCode(const utility::string_t& value)
{
    m_SecondaryCode = value;
    m_SecondaryCodeIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::secondaryCodeIsSet() const
{
    return m_SecondaryCodeIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetSecondaryCode()
{
    m_SecondaryCodeIsSet = false;
}
int64_t UpdateUserNotificationStatus_200_response::getBannedUntil() const
{
    return m_BannedUntil;
}

void UpdateUserNotificationStatus_200_response::setBannedUntil(int64_t value)
{
    m_BannedUntil = value;
    m_BannedUntilIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::bannedUntilIsSet() const
{
    return m_BannedUntilIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetBannedUntil()
{
    m_BannedUntilIsSet = false;
}
int32_t UpdateUserNotificationStatus_200_response::getMaxCharacterLength() const
{
    return m_MaxCharacterLength;
}

void UpdateUserNotificationStatus_200_response::setMaxCharacterLength(int32_t value)
{
    m_MaxCharacterLength = value;
    m_MaxCharacterLengthIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::maxCharacterLengthIsSet() const
{
    return m_MaxCharacterLengthIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetMaxCharacterLength()
{
    m_MaxCharacterLengthIsSet = false;
}
utility::string_t UpdateUserNotificationStatus_200_response::getTranslatedError() const
{
    return m_TranslatedError;
}


void UpdateUserNotificationStatus_200_response::setTranslatedError(const utility::string_t& value)
{
    m_TranslatedError = value;
    m_TranslatedErrorIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::translatedErrorIsSet() const
{
    return m_TranslatedErrorIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetTranslatedError()
{
    m_TranslatedErrorIsSet = false;
}
std::shared_ptr<CustomConfigParameters> UpdateUserNotificationStatus_200_response::getCustomConfig() const
{
    return m_CustomConfig;
}


void UpdateUserNotificationStatus_200_response::setCustomConfig(const std::shared_ptr<CustomConfigParameters>& value)
{
    m_CustomConfig = value;
    m_CustomConfigIsSet = true;
}

bool UpdateUserNotificationStatus_200_response::customConfigIsSet() const
{
    return m_CustomConfigIsSet;
}

void UpdateUserNotificationStatus_200_response::unsetCustomConfig()
{
    m_CustomConfigIsSet = false;
}

}
}
}
}


