/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/UpdateHashTagBody.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UpdateHashTagBody::UpdateHashTagBody()
{
    m_TenantId = utility::conversions::to_string_t("");
    m_TenantIdIsSet = false;
    m_Url = utility::conversions::to_string_t("");
    m_UrlIsSet = false;
    m_Tag = utility::conversions::to_string_t("");
    m_TagIsSet = false;
}

UpdateHashTagBody::~UpdateHashTagBody()
{
}

void UpdateHashTagBody::validate()
{
    // TODO: implement validation
}

web::json::value UpdateHashTagBody::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TenantIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenantId"))] = ModelBase::toJson(m_TenantId);
    }
    if(m_UrlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("url"))] = ModelBase::toJson(m_Url);
    }
    if(m_TagIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tag"))] = ModelBase::toJson(m_Tag);
    }

    return val;
}

bool UpdateHashTagBody::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenantId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantId);
            setTenantId(refVal_setTenantId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrl);
            setUrl(refVal_setUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tag"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tag")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTag;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTag);
            setTag(refVal_setTag);
            
        }
    }
    return ok;
}

void UpdateHashTagBody::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TenantIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenantId")), m_TenantId));
    }
    if(m_UrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("url")), m_Url));
    }
    if(m_TagIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tag")), m_Tag));
    }
}

bool UpdateHashTagBody::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))))
    {
        utility::string_t refVal_setTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenantId"))), refVal_setTenantId );
        setTenantId(refVal_setTenantId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("url"))))
    {
        utility::string_t refVal_setUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("url"))), refVal_setUrl );
        setUrl(refVal_setUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tag"))))
    {
        utility::string_t refVal_setTag;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tag"))), refVal_setTag );
        setTag(refVal_setTag);
    }
    return ok;
}


utility::string_t UpdateHashTagBody::getTenantId() const
{
    return m_TenantId;
}


void UpdateHashTagBody::setTenantId(const utility::string_t& value)
{
    m_TenantId = value;
    m_TenantIdIsSet = true;
}

bool UpdateHashTagBody::tenantIdIsSet() const
{
    return m_TenantIdIsSet;
}

void UpdateHashTagBody::unsetTenantId()
{
    m_TenantIdIsSet = false;
}
utility::string_t UpdateHashTagBody::getUrl() const
{
    return m_Url;
}


void UpdateHashTagBody::setUrl(const utility::string_t& value)
{
    m_Url = value;
    m_UrlIsSet = true;
}

bool UpdateHashTagBody::urlIsSet() const
{
    return m_UrlIsSet;
}

void UpdateHashTagBody::unsetUrl()
{
    m_UrlIsSet = false;
}
utility::string_t UpdateHashTagBody::getTag() const
{
    return m_Tag;
}


void UpdateHashTagBody::setTag(const utility::string_t& value)
{
    m_Tag = value;
    m_TagIsSet = true;
}

bool UpdateHashTagBody::tagIsSet() const
{
    return m_TagIsSet;
}

void UpdateHashTagBody::unsetTag()
{
    m_TagIsSet = false;
}

}
}
}
}


