/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FastCommentsClient/model/UserNotificationCount.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UserNotificationCount::UserNotificationCount()
{
    m__id = utility::conversions::to_string_t("");
    m__idIsSet = false;
    m_Count = 0.0;
    m_CountIsSet = false;
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
    m_ExpireAt = utility::datetime();
    m_ExpireAtIsSet = false;
}

UserNotificationCount::~UserNotificationCount()
{
}

void UserNotificationCount::validate()
{
    // TODO: implement validation
}

web::json::value UserNotificationCount::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m__idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("_id"))] = ModelBase::toJson(m__id);
    }
    if(m_CountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("count"))] = ModelBase::toJson(m_Count);
    }
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_ExpireAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("expireAt"))] = ModelBase::toJson(m_ExpireAt);
    }

    return val;
}

bool UserNotificationCount::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("count")));
        if(!fieldValue.is_null())
        {
            double refVal_setCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCount);
            setCount(refVal_setCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("expireAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("expireAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setExpireAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExpireAt);
            setExpireAt(refVal_setExpireAt);
            
        }
    }
    return ok;
}

void UserNotificationCount::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m__idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("_id")), m__id));
    }
    if(m_CountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("count")), m_Count));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_ExpireAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("expireAt")), m_ExpireAt));
    }
}

bool UserNotificationCount::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("_id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("_id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("count"))))
    {
        double refVal_setCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("count"))), refVal_setCount );
        setCount(refVal_setCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("expireAt"))))
    {
        utility::datetime refVal_setExpireAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("expireAt"))), refVal_setExpireAt );
        setExpireAt(refVal_setExpireAt);
    }
    return ok;
}


utility::string_t UserNotificationCount::getId() const
{
    return m__id;
}


void UserNotificationCount::setId(const utility::string_t& value)
{
    m__id = value;
    m__idIsSet = true;
}

bool UserNotificationCount::idIsSet() const
{
    return m__idIsSet;
}

void UserNotificationCount::unset_id()
{
    m__idIsSet = false;
}
double UserNotificationCount::getCount() const
{
    return m_Count;
}

void UserNotificationCount::setCount(double value)
{
    m_Count = value;
    m_CountIsSet = true;
}

bool UserNotificationCount::countIsSet() const
{
    return m_CountIsSet;
}

void UserNotificationCount::unsetCount()
{
    m_CountIsSet = false;
}
utility::datetime UserNotificationCount::getCreatedAt() const
{
    return m_CreatedAt;
}


void UserNotificationCount::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool UserNotificationCount::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void UserNotificationCount::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
utility::datetime UserNotificationCount::getExpireAt() const
{
    return m_ExpireAt;
}


void UserNotificationCount::setExpireAt(const utility::datetime& value)
{
    m_ExpireAt = value;
    m_ExpireAtIsSet = true;
}

bool UserNotificationCount::expireAtIsSet() const
{
    return m_ExpireAtIsSet;
}

void UserNotificationCount::unsetExpireAt()
{
    m_ExpireAtIsSet = false;
}

}
}
}
}


