/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AggregateResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AggregateResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AggregateResponse_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "FastCommentsClient/model/AggregationResponse.h"
#include "FastCommentsClient/model/AggregationItem.h"
#include <vector>
#include "FastCommentsClient/model/APIStatus.h"
#include "FastCommentsClient/model/AggregationAPIError.h"
#include "FastCommentsClient/model/AggregationResponse_stats.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class AggregationItem;
class AggregationResponse_stats;


class  AggregateResponse
    : public ModelBase
{
public:
    AggregateResponse();
    virtual ~AggregateResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// AggregateResponse members


    std::shared_ptr<APIStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<APIStatus>& value);

    std::vector<std::shared_ptr<AggregationItem>> getData() const;
    bool dataIsSet() const;
    void unsetData();
    void setData(const std::vector<std::shared_ptr<AggregationItem>>& value);

    std::shared_ptr<AggregationResponse_stats> getStats() const;
    bool statsIsSet() const;
    void unsetStats();
    void setStats(const std::shared_ptr<AggregationResponse_stats>& value);

    utility::string_t getReason() const;
    bool reasonIsSet() const;
    void unsetReason();
    void setReason(const utility::string_t& value);

    utility::string_t getCode() const;
    bool codeIsSet() const;
    void unsetCode();
    void setCode(const utility::string_t& value);

    std::vector<utility::string_t> getValidResourceNames() const;
    bool validResourceNamesIsSet() const;
    void unsetValidResourceNames();
    void setValidResourceNames(const std::vector<utility::string_t>& value);


protected:
    std::shared_ptr<APIStatus> m_Status;
    bool m_StatusIsSet;

    std::vector<std::shared_ptr<AggregationItem>> m_Data;
    bool m_DataIsSet;

    std::shared_ptr<AggregationResponse_stats> m_Stats;
    bool m_StatsIsSet;

    utility::string_t m_Reason;
    bool m_ReasonIsSet;

    utility::string_t m_Code;
    bool m_CodeIsSet;

    std::vector<utility::string_t> m_ValidResourceNames;
    bool m_ValidResourceNamesIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AggregateResponse_H_ */
