/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * APIBanUserChangedValues.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_APIBanUserChangedValues_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_APIBanUserChangedValues_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  APIBanUserChangedValues
    : public ModelBase
{
public:
    APIBanUserChangedValues();
    virtual ~APIBanUserChangedValues();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// APIBanUserChangedValues members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unset_id();
    void setId(const utility::string_t& value);

    utility::string_t getTenantId() const;
    bool tenantIdIsSet() const;
    void unsetTenantId();
    void setTenantId(const utility::string_t& value);

    utility::string_t getUserId() const;
    bool userIdIsSet() const;
    void unsetUserId();
    void setUserId(const utility::string_t& value);

    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();
    void setEmail(const utility::string_t& value);

    utility::string_t getUsername() const;
    bool usernameIsSet() const;
    void unsetUsername();
    void setUsername(const utility::string_t& value);

    utility::string_t getIpHash() const;
    bool ipHashIsSet() const;
    void unsetIpHash();
    void setIpHash(const utility::string_t& value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::datetime& value);

    utility::string_t getBannedByUserId() const;
    bool bannedByUserIdIsSet() const;
    void unsetBannedByUserId();
    void setBannedByUserId(const utility::string_t& value);

    utility::string_t getBannedCommentText() const;
    bool bannedCommentTextIsSet() const;
    void unsetBannedCommentText();
    void setBannedCommentText(const utility::string_t& value);

    utility::string_t getBanType() const;
    bool banTypeIsSet() const;
    void unsetBanType();
    void setBanType(const utility::string_t& value);

    utility::datetime getBannedUntil() const;
    bool bannedUntilIsSet() const;
    void unsetBannedUntil();
    void setBannedUntil(const utility::datetime& value);

    bool isHasEmailWildcard() const;
    bool hasEmailWildcardIsSet() const;
    void unsetHasEmailWildcard();
    void setHasEmailWildcard(bool value);

    utility::string_t getBanReason() const;
    bool banReasonIsSet() const;
    void unsetBanReason();
    void setBanReason(const utility::string_t& value);


protected:
    utility::string_t m__id;
    bool m__idIsSet;

    utility::string_t m_TenantId;
    bool m_TenantIdIsSet;

    boost::optional<utility::string_t> m_UserId;

    boost::optional<utility::string_t> m_Email;

    boost::optional<utility::string_t> m_Username;

    boost::optional<utility::string_t> m_IpHash;

    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;

    utility::string_t m_BannedByUserId;
    bool m_BannedByUserIdIsSet;

    utility::string_t m_BannedCommentText;
    bool m_BannedCommentTextIsSet;

    utility::string_t m_BanType;
    bool m_BanTypeIsSet;

    boost::optional<utility::datetime> m_BannedUntil;

    bool m_HasEmailWildcard;
    bool m_HasEmailWildcardIsSet;

    utility::string_t m_BanReason;
    bool m_BanReasonIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_APIBanUserChangedValues_H_ */
