/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * APIBanUserChangeLog.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_APIBanUserChangeLog_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_APIBanUserChangeLog_H_


#include "FastCommentsClient/ModelBase.h"

#include "FastCommentsClient/model/APIBanUserChangedValues.h"
#include "FastCommentsClient/model/APIBannedUser.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class APIBannedUser;
class APIBanUserChangedValues;


class  APIBanUserChangeLog
    : public ModelBase
{
public:
    APIBanUserChangeLog();
    virtual ~APIBanUserChangeLog();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// APIBanUserChangeLog members


    utility::string_t getCreatedBannedUserId() const;
    bool createdBannedUserIdIsSet() const;
    void unsetCreatedBannedUserId();
    void setCreatedBannedUserId(const utility::string_t& value);

    utility::string_t getUpdatedBannedUserId() const;
    bool updatedBannedUserIdIsSet() const;
    void unsetUpdatedBannedUserId();
    void setUpdatedBannedUserId(const utility::string_t& value);

    std::vector<std::shared_ptr<APIBannedUser>> getDeletedBannedUsers() const;
    bool deletedBannedUsersIsSet() const;
    void unsetDeletedBannedUsers();
    void setDeletedBannedUsers(const std::vector<std::shared_ptr<APIBannedUser>>& value);

    std::shared_ptr<APIBanUserChangedValues> getChangedValuesBefore() const;
    bool changedValuesBeforeIsSet() const;
    void unsetChangedValuesBefore();
    void setChangedValuesBefore(const std::shared_ptr<APIBanUserChangedValues>& value);


protected:
    utility::string_t m_CreatedBannedUserId;
    bool m_CreatedBannedUserIdIsSet;

    utility::string_t m_UpdatedBannedUserId;
    bool m_UpdatedBannedUserIdIsSet;

    std::vector<std::shared_ptr<APIBannedUser>> m_DeletedBannedUsers;
    bool m_DeletedBannedUsersIsSet;

    std::shared_ptr<APIBanUserChangedValues> m_ChangedValuesBefore;
    bool m_ChangedValuesBeforeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_APIBanUserChangeLog_H_ */
