/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * APICreateUserBadgeResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_APICreateUserBadgeResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_APICreateUserBadgeResponse_H_

#include <stdexcept>

#include "FastCommentsClient/ModelBase.h"

#include "FastCommentsClient/model/UserBadge.h"
#include "FastCommentsClient/model/APIStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class UserBadge;


class  APICreateUserBadgeResponse
    : public ModelBase
{
public:
    APICreateUserBadgeResponse();
    virtual ~APICreateUserBadgeResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// APICreateUserBadgeResponse members


    std::shared_ptr<APIStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<APIStatus>& value);

    std::shared_ptr<UserBadge> getUserBadge() const;
    bool userBadgeIsSet() const;
    void unsetUserBadge();
    void setUserBadge(const std::shared_ptr<UserBadge>& value);


protected:
    std::shared_ptr<APIStatus> m_Status;
    bool m_StatusIsSet;

    std::shared_ptr<UserBadge> m_UserBadge;
    bool m_UserBadgeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_APICreateUserBadgeResponse_H_ */
