/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * APITicketFile.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_APITicketFile_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_APITicketFile_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  APITicketFile
    : public ModelBase
{
public:
    APITicketFile();
    virtual ~APITicketFile();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// APITicketFile members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    utility::string_t getS3Key() const;
    bool s3KeyIsSet() const;
    void unsetS3Key();
    void setS3Key(const utility::string_t& value);

    utility::string_t getOriginalFileName() const;
    bool originalFileNameIsSet() const;
    void unsetOriginalFileName();
    void setOriginalFileName(const utility::string_t& value);

    int32_t getSizeBytes() const;
    bool sizeBytesIsSet() const;
    void unsetSizeBytes();
    void setSizeBytes(int32_t value);

    utility::string_t getContentType() const;
    bool contentTypeIsSet() const;
    void unsetContentType();
    void setContentType(const utility::string_t& value);

    utility::string_t getUploadedByUserId() const;
    bool uploadedByUserIdIsSet() const;
    void unsetUploadedByUserId();
    void setUploadedByUserId(const utility::string_t& value);

    utility::string_t getUploadedAt() const;
    bool uploadedAtIsSet() const;
    void unsetUploadedAt();
    void setUploadedAt(const utility::string_t& value);

    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();
    void setUrl(const utility::string_t& value);

    utility::string_t getExpiresAt() const;
    bool expiresAtIsSet() const;
    void unsetExpiresAt();
    void setExpiresAt(const utility::string_t& value);

    bool isExpired() const;
    bool expiredIsSet() const;
    void unsetExpired();
    void setExpired(bool value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_S3Key;
    bool m_S3KeyIsSet;

    utility::string_t m_OriginalFileName;
    bool m_OriginalFileNameIsSet;

    int32_t m_SizeBytes;
    bool m_SizeBytesIsSet;

    utility::string_t m_ContentType;
    bool m_ContentTypeIsSet;

    utility::string_t m_UploadedByUserId;
    bool m_UploadedByUserIdIsSet;

    utility::string_t m_UploadedAt;
    bool m_UploadedAtIsSet;

    utility::string_t m_Url;
    bool m_UrlIsSet;

    utility::string_t m_ExpiresAt;
    bool m_ExpiresAtIsSet;

    bool m_Expired;
    bool m_ExpiredIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_APITicketFile_H_ */
