/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BulkAggregateQuestionResultsRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BulkAggregateQuestionResultsRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BulkAggregateQuestionResultsRequest_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include "FastCommentsClient/model/BulkAggregateQuestionItem.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class BulkAggregateQuestionItem;


class  BulkAggregateQuestionResultsRequest
    : public ModelBase
{
public:
    BulkAggregateQuestionResultsRequest();
    virtual ~BulkAggregateQuestionResultsRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// BulkAggregateQuestionResultsRequest members


    std::vector<std::shared_ptr<BulkAggregateQuestionItem>> getAggregations() const;
    bool aggregationsIsSet() const;
    void unsetAggregations();
    void setAggregations(const std::vector<std::shared_ptr<BulkAggregateQuestionItem>>& value);


protected:
    std::vector<std::shared_ptr<BulkAggregateQuestionItem>> m_Aggregations;
    bool m_AggregationsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BulkAggregateQuestionResultsRequest_H_ */
