/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ChangeCommentPinStatusResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ChangeCommentPinStatusResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ChangeCommentPinStatusResponse_H_

#include <stdexcept>

#include "FastCommentsClient/ModelBase.h"

#include "FastCommentsClient/model/Record_string__before_string_or_null__after_string_or_null___value.h"
#include <map>
#include "FastCommentsClient/model/APIStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Record_string__before_string_or_null__after_string_or_null___value;


class  ChangeCommentPinStatusResponse
    : public ModelBase
{
public:
    ChangeCommentPinStatusResponse();
    virtual ~ChangeCommentPinStatusResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ChangeCommentPinStatusResponse members


    /// <summary>
    /// Construct a type with a set of properties K of type T
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<Record_string__before_string_or_null__after_string_or_null___value>> getCommentPositions() const;
    bool commentPositionsIsSet() const;
    void unsetCommentPositions();
    void setCommentPositions(const std::map<utility::string_t, std::shared_ptr<Record_string__before_string_or_null__after_string_or_null___value>>& value);

    std::shared_ptr<APIStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<APIStatus>& value);


protected:
    std::map<utility::string_t, std::shared_ptr<Record_string__before_string_or_null__after_string_or_null___value>> m_CommentPositions;
    bool m_CommentPositionsIsSet;

    std::shared_ptr<APIStatus> m_Status;
    bool m_StatusIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ChangeCommentPinStatusResponse_H_ */
