/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FeedPostStats.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FeedPostStats_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FeedPostStats_H_


#include "FastCommentsClient/ModelBase.h"

#include <map>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  FeedPostStats
    : public ModelBase
{
public:
    FeedPostStats();
    virtual ~FeedPostStats();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// FeedPostStats members


    std::map<utility::string_t, int32_t> getReacts() const;
    bool reactsIsSet() const;
    void unsetReacts();
    void setReacts(std::map<utility::string_t, int32_t> value);

    int32_t getCommentCount() const;
    bool commentCountIsSet() const;
    void unsetCommentCount();
    void setCommentCount(int32_t value);


protected:
    std::map<utility::string_t, int32_t> m_Reacts;
    bool m_ReactsIsSet;

    int32_t m_CommentCount;
    bool m_CommentCountIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FeedPostStats_H_ */
