/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetCommentTextResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GetCommentTextResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GetCommentTextResponse_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "FastCommentsClient/model/APIStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  GetCommentTextResponse
    : public ModelBase
{
public:
    GetCommentTextResponse();
    virtual ~GetCommentTextResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetCommentTextResponse members


    utility::string_t getComment() const;
    bool commentIsSet() const;
    void unsetComment();
    void setComment(const utility::string_t& value);

    std::shared_ptr<APIStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<APIStatus>& value);


protected:
    boost::optional<utility::string_t> m_Comment;

    std::shared_ptr<APIStatus> m_Status;
    bool m_StatusIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GetCommentTextResponse_H_ */
