/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * HeaderState.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_HeaderState_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_HeaderState_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "FastCommentsClient/Object.h"
#include <vector>
#include "FastCommentsClient/model/NotificationAndCount.h"
#include "FastCommentsClient/model/APIStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class NotificationAndCount;


class  HeaderState
    : public ModelBase
{
public:
    HeaderState();
    virtual ~HeaderState();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// HeaderState members


    std::shared_ptr<APIStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<APIStatus>& value);

    std::shared_ptr<Object> getNotificationType() const;
    bool notificationTypeIsSet() const;
    void unsetNotificationType();
    void setNotificationType(const std::shared_ptr<Object>& value);

    utility::string_t getUserId() const;
    bool userIdIsSet() const;
    void unsetUserId();
    void setUserId(const utility::string_t& value);

    utility::string_t getUserIdWS() const;
    bool userIdWSIsSet() const;
    void unsetUserIdWS();
    void setUserIdWS(const utility::string_t& value);

    std::vector<std::shared_ptr<NotificationAndCount>> getNotificationCounts() const;
    bool notificationCountsIsSet() const;
    void unsetNotificationCounts();
    void setNotificationCounts(const std::vector<std::shared_ptr<NotificationAndCount>>& value);


protected:
    std::shared_ptr<APIStatus> m_Status;
    bool m_StatusIsSet;

    std::shared_ptr<Object> m_NotificationType;
    bool m_NotificationTypeIsSet;

    utility::string_t m_UserId;
    bool m_UserIdIsSet;

    utility::string_t m_UserIdWS;
    bool m_UserIdWSIsSet;

    std::vector<std::shared_ptr<NotificationAndCount>> m_NotificationCounts;
    bool m_NotificationCountsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_HeaderState_H_ */
