/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ImageContentProfanityLevel.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ImageContentProfanityLevel_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ImageContentProfanityLevel_H_


#include "FastCommentsClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  ImageContentProfanityLevel
    : public ModelBase
{
public:
    ImageContentProfanityLevel();
    ImageContentProfanityLevel(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~ImageContentProfanityLevel();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eImageContentProfanityLevel
    {
        OFF,
        LOW,
        MEDIUM,
        HIGH,
    };

    eImageContentProfanityLevel getValue() const;
    void setValue(eImageContentProfanityLevel const value);

    protected:
        eImageContentProfanityLevel m_value;
        std::map<eImageContentProfanityLevel,utility::string_t> enumToStrMap = {
        { eImageContentProfanityLevel::OFF, _XPLATSTR("OFF") },
        { eImageContentProfanityLevel::LOW, _XPLATSTR("LOW") },
        { eImageContentProfanityLevel::MEDIUM, _XPLATSTR("MEDIUM") },
        { eImageContentProfanityLevel::HIGH, _XPLATSTR("HIGH") }
};
        std::map<utility::string_t,eImageContentProfanityLevel> strToEnumMap = {
        { _XPLATSTR("OFF"), eImageContentProfanityLevel::OFF },
        { _XPLATSTR("LOW"), eImageContentProfanityLevel::LOW },
        { _XPLATSTR("MEDIUM"), eImageContentProfanityLevel::MEDIUM },
        { _XPLATSTR("HIGH"), eImageContentProfanityLevel::HIGH }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ImageContentProfanityLevel_H_ */
