/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Moderator.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Moderator_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Moderator_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Moderator
    : public ModelBase
{
public:
    Moderator();
    virtual ~Moderator();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Moderator members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unset_id();
    void setId(const utility::string_t& value);

    utility::string_t getTenantId() const;
    bool tenantIdIsSet() const;
    void unsetTenantId();
    void setTenantId(const utility::string_t& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getUserId() const;
    bool userIdIsSet() const;
    void unsetUserId();
    void setUserId(const utility::string_t& value);

    bool isAcceptedInvite() const;
    bool acceptedInviteIsSet() const;
    void unsetAcceptedInvite();
    void setAcceptedInvite(bool value);

    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();
    void setEmail(const utility::string_t& value);

    double getMarkReviewedCount() const;
    bool markReviewedCountIsSet() const;
    void unsetMarkReviewedCount();
    void setMarkReviewedCount(double value);

    double getDeletedCount() const;
    bool deletedCountIsSet() const;
    void unsetDeletedCount();
    void setDeletedCount(double value);

    double getMarkedSpamCount() const;
    bool markedSpamCountIsSet() const;
    void unsetMarkedSpamCount();
    void setMarkedSpamCount(double value);

    double getMarkedNotSpamCount() const;
    bool markedNotSpamCountIsSet() const;
    void unsetMarkedNotSpamCount();
    void setMarkedNotSpamCount(double value);

    double getApprovedCount() const;
    bool approvedCountIsSet() const;
    void unsetApprovedCount();
    void setApprovedCount(double value);

    double getUnApprovedCount() const;
    bool unApprovedCountIsSet() const;
    void unsetUnApprovedCount();
    void setUnApprovedCount(double value);

    double getEditedCount() const;
    bool editedCountIsSet() const;
    void unsetEditedCount();
    void setEditedCount(double value);

    double getBannedCount() const;
    bool bannedCountIsSet() const;
    void unsetBannedCount();
    void setBannedCount(double value);

    double getUnFlaggedCount() const;
    bool unFlaggedCountIsSet() const;
    void unsetUnFlaggedCount();
    void setUnFlaggedCount(double value);

    utility::string_t getVerificationId() const;
    bool verificationIdIsSet() const;
    void unsetVerificationId();
    void setVerificationId(const utility::string_t& value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::datetime& value);

    std::vector<utility::string_t> getModerationGroupIds() const;
    bool moderationGroupIdsIsSet() const;
    void unsetModerationGroupIds();
    void setModerationGroupIds(const std::vector<utility::string_t>& value);


protected:
    utility::string_t m__id;
    bool m__idIsSet;

    utility::string_t m_TenantId;
    bool m_TenantIdIsSet;

    boost::optional<utility::string_t> m_Name;

    boost::optional<utility::string_t> m_UserId;

    bool m_AcceptedInvite;
    bool m_AcceptedInviteIsSet;

    boost::optional<utility::string_t> m_Email;

    double m_MarkReviewedCount;
    bool m_MarkReviewedCountIsSet;

    double m_DeletedCount;
    bool m_DeletedCountIsSet;

    double m_MarkedSpamCount;
    bool m_MarkedSpamCountIsSet;

    double m_MarkedNotSpamCount;
    bool m_MarkedNotSpamCountIsSet;

    double m_ApprovedCount;
    bool m_ApprovedCountIsSet;

    double m_UnApprovedCount;
    bool m_UnApprovedCountIsSet;

    double m_EditedCount;
    bool m_EditedCountIsSet;

    double m_BannedCount;
    bool m_BannedCountIsSet;

    double m_UnFlaggedCount;
    bool m_UnFlaggedCountIsSet;

    boost::optional<utility::string_t> m_VerificationId;

    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;

    boost::optional<std::vector<utility::string_t>> m_ModerationGroupIds;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Moderator_H_ */
