/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ModerationPageSearchResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ModerationPageSearchResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ModerationPageSearchResponse_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include "FastCommentsClient/model/ModerationPageSearchProjected.h"
#include <vector>
#include "FastCommentsClient/model/APIStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ModerationPageSearchProjected;


class  ModerationPageSearchResponse
    : public ModelBase
{
public:
    ModerationPageSearchResponse();
    virtual ~ModerationPageSearchResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ModerationPageSearchResponse members


    std::vector<std::shared_ptr<ModerationPageSearchProjected>> getPages() const;
    bool pagesIsSet() const;
    void unsetPages();
    void setPages(const std::vector<std::shared_ptr<ModerationPageSearchProjected>>& value);

    std::shared_ptr<APIStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<APIStatus>& value);


protected:
    std::vector<std::shared_ptr<ModerationPageSearchProjected>> m_Pages;
    bool m_PagesIsSet;

    std::shared_ptr<APIStatus> m_Status;
    bool m_StatusIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ModerationPageSearchResponse_H_ */
