/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ModerationAPICommentLog.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ModerationAPICommentLog_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ModerationAPICommentLog_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  ModerationAPICommentLog
    : public ModelBase
{
public:
    ModerationAPICommentLog();
    virtual ~ModerationAPICommentLog();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ModerationAPICommentLog members


    utility::datetime getDate() const;
    bool dateIsSet() const;
    void unsetdate();
    void setDate(const utility::datetime& value);

    utility::string_t getUsername() const;
    bool usernameIsSet() const;
    void unsetUsername();
    void setUsername(const utility::string_t& value);

    utility::string_t getActionName() const;
    bool actionNameIsSet() const;
    void unsetActionName();
    void setActionName(const utility::string_t& value);

    utility::string_t getMessageHTML() const;
    bool messageHTMLIsSet() const;
    void unsetMessageHTML();
    void setMessageHTML(const utility::string_t& value);


protected:
    utility::datetime m_date;
    bool m_dateIsSet;

    utility::string_t m_Username;
    bool m_UsernameIsSet;

    utility::string_t m_ActionName;
    bool m_ActionNameIsSet;

    utility::string_t m_MessageHTML;
    bool m_MessageHTMLIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ModerationAPICommentLog_H_ */
