/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PatchDomainConfigResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PatchDomainConfigResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PatchDomainConfigResponse_H_


#include "FastCommentsClient/ModelBase.h"

#include "FastCommentsClient/model/GetDomainConfigsResponse_anyOf_1.h"
#include "FastCommentsClient/model/AddDomainConfigResponse_anyOf.h"
#include <cpprest/details/basic_types.h>
#include "FastCommentsClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  PatchDomainConfigResponse
    : public ModelBase
{
public:
    PatchDomainConfigResponse();
    virtual ~PatchDomainConfigResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// PatchDomainConfigResponse members


    std::shared_ptr<Object> getConfiguration() const;
    bool configurationIsSet() const;
    void unsetConfiguration();
    void setConfiguration(const std::shared_ptr<Object>& value);

    std::shared_ptr<Object> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<Object>& value);

    utility::string_t getReason() const;
    bool reasonIsSet() const;
    void unsetReason();
    void setReason(const utility::string_t& value);

    utility::string_t getCode() const;
    bool codeIsSet() const;
    void unsetCode();
    void setCode(const utility::string_t& value);


protected:
    std::shared_ptr<Object> m_Configuration;
    bool m_ConfigurationIsSet;

    std::shared_ptr<Object> m_Status;
    bool m_StatusIsSet;

    utility::string_t m_Reason;
    bool m_ReasonIsSet;

    utility::string_t m_Code;
    bool m_CodeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PatchDomainConfigResponse_H_ */
