/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.18.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PubSubCommentBase.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PubSubCommentBase_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PubSubCommentBase_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include "FastCommentsClient/model/CommentUserBadgeInfo.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class CommentUserBadgeInfo;


class  PubSubCommentBase
    : public ModelBase
{
public:
    PubSubCommentBase();
    virtual ~PubSubCommentBase();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// PubSubCommentBase members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unset_id();
    void setId(const utility::string_t& value);

    utility::string_t getTenantId() const;
    bool tenantIdIsSet() const;
    void unsetTenantId();
    void setTenantId(const utility::string_t& value);

    utility::string_t getUserId() const;
    bool userIdIsSet() const;
    void unsetUserId();
    void setUserId(const utility::string_t& value);

    utility::string_t getUrlId() const;
    bool urlIdIsSet() const;
    void unsetUrlId();
    void setUrlId(const utility::string_t& value);

    utility::string_t getCommenterName() const;
    bool commenterNameIsSet() const;
    void unsetCommenterName();
    void setCommenterName(const utility::string_t& value);

    utility::string_t getCommenterLink() const;
    bool commenterLinkIsSet() const;
    void unsetCommenterLink();
    void setCommenterLink(const utility::string_t& value);

    utility::string_t getCommentHTML() const;
    bool commentHTMLIsSet() const;
    void unsetCommentHTML();
    void setCommentHTML(const utility::string_t& value);

    utility::string_t getComment() const;
    bool commentIsSet() const;
    void unsetComment();
    void setComment(const utility::string_t& value);

    utility::string_t getParentId() const;
    bool parentIdIsSet() const;
    void unsetParentId();
    void setParentId(const utility::string_t& value);

    int32_t getVotes() const;
    bool votesIsSet() const;
    void unsetVotes();
    void setVotes(int32_t value);

    int32_t getVotesUp() const;
    bool votesUpIsSet() const;
    void unsetVotesUp();
    void setVotesUp(int32_t value);

    int32_t getVotesDown() const;
    bool votesDownIsSet() const;
    void unsetVotesDown();
    void setVotesDown(int32_t value);

    bool isVerified() const;
    bool verifiedIsSet() const;
    void unsetVerified();
    void setVerified(bool value);

    utility::string_t getAvatarSrc() const;
    bool avatarSrcIsSet() const;
    void unsetAvatarSrc();
    void setAvatarSrc(const utility::string_t& value);

    bool isHasImages() const;
    bool hasImagesIsSet() const;
    void unsetHasImages();
    void setHasImages(bool value);

    bool isHasLinks() const;
    bool hasLinksIsSet() const;
    void unsetHasLinks();
    void setHasLinks(bool value);

    bool isIsByAdmin() const;
    bool isByAdminIsSet() const;
    void unsetIsByAdmin();
    void setIsByAdmin(bool value);

    bool isIsByModerator() const;
    bool isByModeratorIsSet() const;
    void unsetIsByModerator();
    void setIsByModerator(bool value);

    bool isIsPinned() const;
    bool isPinnedIsSet() const;
    void unsetIsPinned();
    void setIsPinned(bool value);

    bool isIsLocked() const;
    bool isLockedIsSet() const;
    void unsetIsLocked();
    void setIsLocked(bool value);

    utility::string_t getDisplayLabel() const;
    bool displayLabelIsSet() const;
    void unsetDisplayLabel();
    void setDisplayLabel(const utility::string_t& value);

    double getRating() const;
    bool ratingIsSet() const;
    void unsetRating();
    void setRating(double value);

    std::vector<std::shared_ptr<CommentUserBadgeInfo>> getBadges() const;
    bool badgesIsSet() const;
    void unsetBadges();
    void setBadges(const std::vector<std::shared_ptr<CommentUserBadgeInfo>>& value);

    int64_t getViewCount() const;
    bool viewCountIsSet() const;
    void unsetViewCount();
    void setViewCount(int64_t value);

    bool isIsDeleted() const;
    bool isDeletedIsSet() const;
    void unsetIsDeleted();
    void setIsDeleted(bool value);

    bool isIsDeletedUser() const;
    bool isDeletedUserIsSet() const;
    void unsetIsDeletedUser();
    void setIsDeletedUser(bool value);

    bool isIsSpam() const;
    bool isSpamIsSet() const;
    void unsetIsSpam();
    void setIsSpam(bool value);

    utility::string_t getAnonUserId() const;
    bool anonUserIdIsSet() const;
    void unsetAnonUserId();
    void setAnonUserId(const utility::string_t& value);

    std::vector<utility::string_t> getFeedbackIds() const;
    bool feedbackIdsIsSet() const;
    void unsetFeedbackIds();
    void setFeedbackIds(const std::vector<utility::string_t>& value);

    int32_t getFlagCount() const;
    bool flagCountIsSet() const;
    void unsetFlagCount();
    void setFlagCount(int32_t value);

    utility::string_t getDomain() const;
    bool domainIsSet() const;
    void unsetDomain();
    void setDomain(const utility::string_t& value);

    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();
    void setUrl(const utility::string_t& value);

    utility::string_t getPageTitle() const;
    bool pageTitleIsSet() const;
    void unsetPageTitle();
    void setPageTitle(const utility::string_t& value);

    utility::datetime getExpireAt() const;
    bool expireAtIsSet() const;
    void unsetExpireAt();
    void setExpireAt(const utility::datetime& value);

    bool isReviewed() const;
    bool reviewedIsSet() const;
    void unsetReviewed();
    void setReviewed(bool value);

    bool isHasCode() const;
    bool hasCodeIsSet() const;
    void unsetHasCode();
    void setHasCode(bool value);

    bool isApproved() const;
    bool approvedIsSet() const;
    void unsetApproved();
    void setApproved(bool value);

    utility::string_t getLocale() const;
    bool localeIsSet() const;
    void unsetLocale();
    void setLocale(const utility::string_t& value);

    bool isIsBannedUser() const;
    bool isBannedUserIsSet() const;
    void unsetIsBannedUser();
    void setIsBannedUser(bool value);

    std::vector<utility::string_t> getGroupIds() const;
    bool groupIdsIsSet() const;
    void unsetGroupIds();
    void setGroupIds(const std::vector<utility::string_t>& value);


protected:
    utility::string_t m__id;
    bool m__idIsSet;

    utility::string_t m_TenantId;
    bool m_TenantIdIsSet;

    boost::optional<utility::string_t> m_UserId;

    utility::string_t m_UrlId;
    bool m_UrlIdIsSet;

    utility::string_t m_CommenterName;
    bool m_CommenterNameIsSet;

    boost::optional<utility::string_t> m_CommenterLink;

    utility::string_t m_CommentHTML;
    bool m_CommentHTMLIsSet;

    utility::string_t m_Comment;
    bool m_CommentIsSet;

    boost::optional<utility::string_t> m_ParentId;

    boost::optional<int32_t> m_Votes;

    boost::optional<int32_t> m_VotesUp;

    boost::optional<int32_t> m_VotesDown;

    bool m_Verified;
    bool m_VerifiedIsSet;

    boost::optional<utility::string_t> m_AvatarSrc;

    bool m_HasImages;
    bool m_HasImagesIsSet;

    bool m_HasLinks;
    bool m_HasLinksIsSet;

    bool m_IsByAdmin;
    bool m_IsByAdminIsSet;

    bool m_IsByModerator;
    bool m_IsByModeratorIsSet;

    boost::optional<bool> m_IsPinned;

    boost::optional<bool> m_IsLocked;

    boost::optional<utility::string_t> m_DisplayLabel;

    boost::optional<double> m_Rating;

    boost::optional<std::vector<std::shared_ptr<CommentUserBadgeInfo>>> m_Badges;

    boost::optional<int64_t> m_ViewCount;

    bool m_IsDeleted;
    bool m_IsDeletedIsSet;

    bool m_IsDeletedUser;
    bool m_IsDeletedUserIsSet;

    bool m_IsSpam;
    bool m_IsSpamIsSet;

    boost::optional<utility::string_t> m_AnonUserId;

    std::vector<utility::string_t> m_FeedbackIds;
    bool m_FeedbackIdsIsSet;

    boost::optional<int32_t> m_FlagCount;

    boost::optional<utility::string_t> m_Domain;

    utility::string_t m_Url;
    bool m_UrlIsSet;

    boost::optional<utility::string_t> m_PageTitle;

    boost::optional<utility::datetime> m_ExpireAt;

    bool m_Reviewed;
    bool m_ReviewedIsSet;

    bool m_HasCode;
    bool m_HasCodeIsSet;

    bool m_Approved;
    bool m_ApprovedIsSet;

    boost::optional<utility::string_t> m_Locale;

    bool m_IsBannedUser;
    bool m_IsBannedUserIsSet;

    boost::optional<std::vector<utility::string_t>> m_GroupIds;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PubSubCommentBase_H_ */
