/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdateEmailTemplateBody.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateEmailTemplateBody_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateEmailTemplateBody_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include "FastCommentsClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  UpdateEmailTemplateBody
    : public ModelBase
{
public:
    UpdateEmailTemplateBody();
    virtual ~UpdateEmailTemplateBody();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UpdateEmailTemplateBody members


    utility::string_t getEmailTemplateId() const;
    bool emailTemplateIdIsSet() const;
    void unsetEmailTemplateId();
    void setEmailTemplateId(const utility::string_t& value);

    utility::string_t getDisplayName() const;
    bool displayNameIsSet() const;
    void unsetDisplayName();
    void setDisplayName(const utility::string_t& value);

    utility::string_t getEjs() const;
    bool ejsIsSet() const;
    void unsetEjs();
    void setEjs(const utility::string_t& value);

    utility::string_t getDomain() const;
    bool domainIsSet() const;
    void unsetDomain();
    void setDomain(const utility::string_t& value);

    /// <summary>
    /// Construct a type with a set of properties K of type T
    /// </summary>
    std::map<utility::string_t, std::map<utility::string_t, utility::string_t>> getTranslationOverridesByLocale() const;
    bool translationOverridesByLocaleIsSet() const;
    void unsetTranslationOverridesByLocale();
    void setTranslationOverridesByLocale(const std::map<utility::string_t, std::map<utility::string_t, utility::string_t>>& value);

    /// <summary>
    /// Construct a type with a set of properties K of type T
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<AnyType>> getTestData() const;
    bool testDataIsSet() const;
    void unsetTestData();
    void setTestData(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);


protected:
    utility::string_t m_EmailTemplateId;
    bool m_EmailTemplateIdIsSet;

    utility::string_t m_DisplayName;
    bool m_DisplayNameIsSet;

    utility::string_t m_Ejs;
    bool m_EjsIsSet;

    utility::string_t m_Domain;
    bool m_DomainIsSet;

    std::map<utility::string_t, std::map<utility::string_t, utility::string_t>> m_TranslationOverridesByLocale;
    bool m_TranslationOverridesByLocaleIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_TestData;
    bool m_TestDataIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateEmailTemplateBody_H_ */
