/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdateAPIPageData.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateAPIPageData_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateAPIPageData_H_


#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  UpdateAPIPageData
    : public ModelBase
{
public:
    UpdateAPIPageData();
    virtual ~UpdateAPIPageData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UpdateAPIPageData members


    bool isIsClosed() const;
    bool isClosedIsSet() const;
    void unsetIsClosed();
    void setIsClosed(bool value);

    std::vector<utility::string_t> getAccessibleByGroupIds() const;
    bool accessibleByGroupIdsIsSet() const;
    void unsetAccessibleByGroupIds();
    void setAccessibleByGroupIds(const std::vector<utility::string_t>& value);

    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();
    void setTitle(const utility::string_t& value);

    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();
    void setUrl(const utility::string_t& value);

    utility::string_t getUrlId() const;
    bool urlIdIsSet() const;
    void unsetUrlId();
    void setUrlId(const utility::string_t& value);


protected:
    bool m_IsClosed;
    bool m_IsClosedIsSet;

    std::vector<utility::string_t> m_AccessibleByGroupIds;
    bool m_AccessibleByGroupIdsIsSet;

    utility::string_t m_Title;
    bool m_TitleIsSet;

    utility::string_t m_Url;
    bool m_UrlIsSet;

    utility::string_t m_UrlId;
    bool m_UrlIdIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateAPIPageData_H_ */
