/**
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UserPresenceData.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UserPresenceData_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UserPresenceData_H_

#include <boost/optional.hpp>

#include "FastCommentsClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  UserPresenceData
    : public ModelBase
{
public:
    UserPresenceData();
    virtual ~UserPresenceData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UserPresenceData members


    utility::string_t getUrlIdWS() const;
    bool urlIdWSIsSet() const;
    void unsetUrlIdWS();
    void setUrlIdWS(const utility::string_t& value);

    utility::string_t getUserIdWS() const;
    bool userIdWSIsSet() const;
    void unsetUserIdWS();
    void setUserIdWS(const utility::string_t& value);

    utility::string_t getTenantIdWS() const;
    bool tenantIdWSIsSet() const;
    void unsetTenantIdWS();
    void setTenantIdWS(const utility::string_t& value);


protected:
    utility::string_t m_UrlIdWS;
    bool m_UrlIdWSIsSet;

    utility::string_t m_UserIdWS;
    bool m_UserIdWSIsSet;

    utility::string_t m_TenantIdWS;
    bool m_TenantIdWSIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UserPresenceData_H_ */
